'use strict';
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{pathToFileURL}=require('url'),{playwright:pw,launchOptions}=require('./browser_runtime');
const B=path.resolve(__dirname,'..'),source=process.env.STUDIO_INTERACTION_DOCUMENT,out=path.join(B,'qa/shared-symmetry',source?'private':'public');fs.mkdirSync(out,{recursive:true});
const doc=source?JSON.parse(fs.readFileSync(source,'utf8').match(/<script id="pipeline-document" type="application\/json">([\s\S]*?)<\/script>/)[1]):{format:'pipeline-studio',schemaVersion:6,id:'shared',title:'Shared and paired symmetry',materials:[],pages:[{...require('./test_shared_symmetry').fixture(),id:'shared',title:'Shared workflow'},{...require('./test_paired_routes').fixture(),id:'paired',title:'Paired routes'}]};
(async()=>{const b=await pw.chromium.launch(launchOptions),p=await b.newPage({viewport:{width:1700,height:1150}}),checks=[],errors=[],records=[];p.on('pageerror',e=>errors.push(e.message));const check=(name,ok)=>{assert(ok,name);checks.push(name);console.log('PASS',name);};
const reset=async(index,compact=true,autoSpace=true,gap=64)=>p.evaluate(async({doc,index,compact,autoSpace,gap})=>{const s=Studio.state;s.dirty=s.fileDirty=false;await Studio.activateDocument(doc,{name:'Symmetry test copy.html',readOnly:false});s.pageIndex=index;s.compact=compact;s.folded=new Set();s.collapsed=Object.fromEntries(s.project.pages.map(p=>[p.id,new Set()]));s.collapsedRows={};s.editModes={};s.selected.clear();s.selectedEdges.clear();s.selectedBuses.clear();s.selectedEdge=s.selectedBus=null;s.project.pages[index].layoutOptions={...s.project.pages[index].layoutOptions,autoSpace,pipelineGap:gap};Studio.render();},{doc,index,compact,autoSpace,gap});
const photographPair=async name=>{await p.evaluate(()=>{const s=Studio.state,C=Studio.Core,pg=s.project.pages[s.pageIndex],set=pg.symmetrySets.find(g=>g.edges.length===4),heads=set.edges.map(id=>pg.edges.find(e=>e.id===id).target),ids=set.edges.flatMap(id=>{const e=pg.edges.find(e=>e.id===id);return [e.source,e.target];});Studio.fit([...ids,...C.exclusiveBranches(pg,heads).flatMap(b=>[...b.ids])]);document.querySelector('#toast').style.visibility='hidden';});await p.locator('#stage').screenshot({path:path.join(out,name)});await p.evaluate(()=>document.querySelector('#toast').style.visibility='');};
try{await p.goto(pathToFileURL(path.join(B,'Pipeline-Studio.html')).href);await p.waitForSelector('#home-new');await p.addScriptTag({path:path.join(B,'tests/layout_audit.js')});
for(const compact of [false,true])for(const autoSpace of [false,true])for(const gap of [24,64,200,600]){await reset(0,compact,autoSpace,gap);const record=await p.evaluate(()=>{const s=Studio.state,C=Studio.Core,pg=s.project.pages[0],bus=pg.buses.find(b=>b.mode==='free'&&b.symmetry),edges=pg.edges.filter(e=>e.bus===bus.id),roots=[...new Set(edges.map(e=>e.source))],ar=pg.nodes.find(n=>/^АР(\s|$)/.test(n.title)||n.id==='ar'),unit=C.layoutUnits(pg).find(u=>roots.every(id=>u.members.has(id))),others=C.layoutUnits(pg).flatMap(u=>u.heads).filter(id=>!roots.includes(id)&&id!==ar.id),before=JSON.stringify(pg.nodes),snapshot=folded=>{s.collapsed[pg.id]=new Set([...others,...folded?[ar.id]:[]]);Studio.render();const a=LayoutAudit.audit(C,pg,s.display);return {positions:s.display.nodes.filter(n=>unit.members.has(n.id)).map(n=>({id:n.id,x:n.x,y:n.y})),symmetry:a.symmetry.filter(g=>g.id===bus.id),issues:a.issues};},closed=snapshot(true),open=snapshot(false),again=snapshot(true);return {closed,open,again,pure:before===JSON.stringify(pg.nodes)};});
const a=record.closed.positions[0],o=record.open.positions.find(n=>n.id===a.id),dx=o.x-a.x,dy=o.y-a.y,uniform=record.closed.positions.every(n=>{const v=record.open.positions.find(v=>v.id===n.id);return v&&Math.abs(v.x-n.x-dx)<.01&&Math.abs(v.y-n.y-dy)<.01;});check(`Shared layout: compact ${compact}, spacing ${autoSpace}, gap ${gap} keeps the centre and order through AR folding`,[record.closed,record.open].every(r=>r.symmetry.every(g=>g.error<.01&&g.orderError<.01&&g.stepError<.01))&&uniform);check('AR fold-expand cycles preserve the whole shared arrangement and authored data',record.pure&&JSON.stringify(record.closed.positions)===JSON.stringify(record.again.positions));records.push({compact,autoSpace,gap,...record});}
await reset(0);for(const folded of [true,false]){await p.evaluate(folded=>{const s=Studio.state,pg=s.project.pages[0],ar=pg.nodes.find(n=>/^АР(\s|$)/.test(n.title)||n.id==='ar'),bus=pg.buses.find(b=>b.mode==='free'&&b.symmetry),ids=[...new Set(pg.edges.filter(e=>e.bus===bus.id).flatMap(e=>[e.source,e.target]))];s.collapsed[pg.id]=new Set(folded?[ar.id]:[]);Studio.render();const roots=[...new Set(pg.edges.filter(e=>e.bus===bus.id).map(e=>e.source))],unit=Studio.Core.layoutUnits(pg).find(u=>roots.every(id=>u.members.has(id)));Studio.fit(unit?[...unit.members]:ids);},folded);await p.locator('#stage').screenshot({path:path.join(out,folded?'ar-closed.png':'ar-open.png')});}
const pageIndex=doc.pages.findIndex(p=>p.symmetrySets?.some(g=>g.edges.length===4));assert(pageIndex>=0,'Four-edge constraint fixture');await reset(pageIndex);const heads=await p.evaluate(()=>{const s=Studio.state,pg=s.project.pages[s.pageIndex],set=pg.symmetrySets.find(g=>g.edges.length===4);return set.edges.map(id=>pg.edges.find(e=>e.id===id).target);});let limited=0,gestures=0;
for(const head of heads){await reset(pageIndex);if(head===heads[0])await photographPair('paired-original.png');const baseline=await p.evaluate(()=>{const s=Studio.state;window.qaPairBaseline=LayoutAudit.audit(Studio.Core,s.project.pages[s.pageIndex],s.display);return JSON.stringify(s.display.nodes.map(n=>[n.id,n.x,n.y]));});for(const dx of [-40,-40,60,-180,100,-600,180]){await p.evaluate(head=>{const s=Studio.state;s.selected.clear();s.selectedEdges.clear();s.selectedEdge=s.selectedBus=null;s.view.z=.7;Studio.focusNode(head);},head);const rect=await p.locator('#nodes>[data-node="'+head+'"] .node-body').boundingBox(),start={x:rect.x+rect.width/2,y:rect.y+Math.min(20,rect.height/2)},z=await p.evaluate(()=>Studio.state.view.z);await p.mouse.move(start.x,start.y);await p.mouse.down();for(let step=1;step<=3;step++){await p.mouse.move(start.x+dx*z*step/3,start.y);await p.evaluate(()=>new Promise(requestAnimationFrame));const state=await p.evaluate(()=>{const s=Studio.state,pg=s.project.pages[s.pageIndex],set=pg.symmetrySets.find(g=>g.edges.length===4),a=LayoutAudit.audit(Studio.Core,pg,s.display);return {route:a.routeSymmetry.find(g=>g.id===set.id),centres:a.symmetry,added:LayoutAudit.added(window.qaPairBaseline,a),limited:s.dragMovement?.feedback?.limited};});check('Live horizontal movement keeps every paired bend and symmetry centre',state.route.status==='checked'&&state.route.error<.01&&state.centres.every(g=>g.error<.01&&g.stepError<.01)&&!state.added.length);if(state.limited)limited++;}await p.mouse.up();const state=await p.evaluate(()=>{const s=Studio.state,pg=s.project.pages[s.pageIndex],set=pg.symmetrySets.find(g=>g.edges.length===4),a=LayoutAudit.audit(Studio.Core,pg,s.display);return {route:a.routeSymmetry.find(g=>g.id===set.id),centres:a.symmetry,added:LayoutAudit.added(window.qaPairBaseline,a)};});check('Released horizontal movement preserves the same paired route shape',state.route.error<.01&&state.centres.every(g=>g.error<.01&&g.stepError<.01)&&!state.added.length);gestures++;if(head===heads[0]&&dx===-600)await photographPair('paired-close.png');}
await p.evaluate(async()=>{while(Studio.state.history.length)await Studio.undo();});check('Undo restores the exact arrangement before the close-and-return sequence',await p.evaluate(baseline=>JSON.stringify(Studio.state.display.nodes.map(n=>[n.id,n.x,n.y]))===baseline,baseline));}
check('Impossible proximity produces a visible movement limit',limited>0);check('No JavaScript errors occur',!errors.length);await p.evaluate(()=>{const s=Studio.state,pg=s.project.pages[s.pageIndex],set=pg.symmetrySets.find(g=>g.edges.length===4);Studio.fit(set.edges.flatMap(id=>{const e=pg.edges.find(e=>e.id===id);return [e.source,e.target];}));});await p.locator('#stage').screenshot({path:path.join(out,'paired-after.png')});records.push({gestures,limited});
}finally{fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({privateDocument:!!source,checks,errors,records},null,2));await b.close();}console.log('TOTAL',checks.length);})().catch(e=>{console.error(e);process.exitCode=1;});
