'use strict';
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{playwright:pw,launchOptions}=require('./browser_runtime');
const B=path.resolve(__dirname,'..'),out=path.resolve(process.env.STUDIO_SYMMETRY_QA||path.join(B,'qa/symmetry-lab'));fs.mkdirSync(out,{recursive:true});
const source=process.env.STUDIO_PRIVATE_DOCUMENT,doc=source?JSON.parse(fs.readFileSync(source,'utf8').match(/<script id="pipeline-document" type="application\/json">([\s\S]*?)<\/script>/)[1]):JSON.parse(fs.readFileSync(path.join(B,'app/data/seed.json'),'utf8'));
(async()=>{const browser=await pw.chromium.launch(launchOptions),p=await browser.newPage({viewport:{width:1800,height:1150}}),errors=[],runs=[],failures=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(15000);
try{await p.goto('file:///'+path.join(B,'Pipeline-Studio.html').replaceAll('\\','/'));await p.waitForSelector('#home-new');await p.evaluate(doc=>{window.LAB_DOCUMENT=doc;},doc);for(const file of ['tests/layout_audit.js','tests/symmetry_scenarios.js','tools/layout_lab.js'])await p.addScriptTag({path:path.join(B,file)});await p.waitForFunction(()=>window.LayoutLab?.ready);
for(let pageIndex=0;pageIndex<doc.pages.length;pageIndex++){await p.evaluate(i=>{document.getElementById('lab-page').value=String(i);return document.getElementById('lab-page').onchange();},pageIndex);const scenarios=await p.evaluate(()=>LayoutLab.choices());
for(const compact of [false,true])for(const space of [false,true]){await p.locator('#lab-compact').setChecked(compact);await p.locator('#lab-space').setChecked(space);for(const scenario of scenarios){const entry=await p.evaluate(id=>LayoutLab.reset(id),scenario.id);await p.evaluate(()=>new Promise(requestAnimationFrame));const actual=await p.evaluate(()=>LayoutLab.audit());const relevant=new Set(scenario.edges),group=actual.symmetry.find(g=>g.heads.length===scenario.edges.length&&scenario.edges.length>1&&g.heads.every(id=>doc.pages[pageIndex].edges.some(e=>relevant.has(e.id)&&e.target===id)));
const bad=actual.newIssues,result={pageIndex,scenario:scenario.id,title:scenario.title,compact,space,blocked:actual.blocked,newIssues:bad,symmetryError:group?.error||0,stepError:group?.stepError||0,issueCounts:Object.fromEntries(['blocks','line-block','lines'].map(kind=>[kind,actual.issues.filter(i=>i.kind===kind).length]))};runs.push(result);if(bad.length||result.symmetryError>.01||result.stepError>.01){failures.push(result);await p.locator('#stage').screenshot({path:path.join(out,'failure-'+runs.length+'.png')});}
if(!compact&&!space&&(scenario.id.startsWith('all:')||scenario.id.startsWith('four:')||scenario.id==='original')){await p.locator('#stage').screenshot({path:path.join(out,'page-'+pageIndex+'-'+scenario.id.replace(/[^a-zA-Z0-9-]/g,'_')+'.png')});}
if(scenario.id.startsWith('four:')){const first=await p.evaluate(()=>Studio.state.display.nodes.map(n=>[n.id,n.x,n.y]));await p.locator('#lab-fold').click();await p.locator('#lab-expand').click();await p.evaluate(()=>LayoutLab.focus());const again=await p.evaluate(()=>Studio.state.display.nodes.map(n=>[n.id,n.x,n.y]));const delta=first.filter(a=>{const b=again.find(b=>b[0]===a[0]);return !b||Math.abs(a[1]-b[1])>.01||Math.abs(a[2]-b[2])>.01;});if(delta.length||first.length!==again.length)failures.push({...result,cycleDrift:true,delta});}
}
console.log('CHECKED page',pageIndex,'compact',compact,'space',space,'scenarios',scenarios.length);}
}
// Exercise the actual inspector apply button on the exact four-condition case.
await p.locator('#lab-compact').uncheck();await p.locator('#lab-space').uncheck();await p.evaluate(()=>LayoutLab.reset('original'));const four=await p.evaluate(()=>LayoutLab.choices().find(s=>s.id.startsWith('four:')));if(four){await p.evaluate(ids=>{const s=Studio.state;s.selected.clear();s.selectedEdges=new Set(ids);s.selectedBuses=new Set();s.selectedEdge=null;Studio.render();},four.edges);assert(!await p.locator('#selected-symmetry-crossings').isChecked());await p.locator('[data-action="selected-symmetry-align"]').click();await p.evaluate(()=>LayoutLab.focus());const report=await p.evaluate(()=>LayoutLab.audit());assert(!report.newIssues.some(i=>i.kind!=='lines'||i.ids.every(id=>four.edges.includes(id))));await p.locator('#stage').screenshot({path:path.join(out,'inspector-four.png')});await p.evaluate(()=>Studio.undo());await p.evaluate(()=>Studio.redo());assert((await p.evaluate(()=>LayoutLab.audit())).newIssues.filter(i=>i.kind==='blocks').length===0);}
assert(errors.length===0,errors.join('\n'));
}finally{fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({privateDocument:!!source,pages:doc.pages.length,runs:runs.length,scenarios:runs,failures,errors,chromium:browser.version()},null,2));await browser.close();}
console.log('TOTAL',runs.length,'FAILURES',failures.length);assert(failures.length===0,JSON.stringify(failures.slice(0,5),null,2));})().catch(e=>{console.error(e);process.exitCode=1;});
