'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{playwright:pw,launchOptions}=require('./browser_runtime');
const B=path.resolve(__dirname,'..'),out=path.join(B,'qa/view-anchors');fs.mkdirSync(out,{recursive:true});
const checks=[],errors=[],check=(name,ok)=>{checks.push({name,pass:!!ok});console.log(ok?'PASS':'FAIL',name);};
const n=(id,x,y,extra={})=>({id,type:'block',title:id,x,y,w:120,h:60,relativeLock:true,collapsible:true,materials:[],icons:[],...extra});
const e=(id,source,target,extra={})=>({id,source,target,sourcePort:'right',targetPort:'left',arrow:true,...extra});
const fixture=()=>({id:'view-anchors',format:'pipeline-studio',schemaVersion:6,title:'Гребёнка и статусы',materials:[],pages:[{id:'p',title:'Лист',collapseMode:'nodes',nodes:[n('pd',-250,2400,{title:'ПД',collapsible:false}),n('ar',0,0,{title:'АР'}),n('vk',0,300,{title:'ВК',fill:'#d5e8d4'}),n('ov',0,600,{title:'ОВ',fill:'#dae8fc'}),n('ar-tail',400,1000),n('vk-tail',400,1800),n('ov-tail',400,3000)],edges:[e('pa','pd','ar',{bus:'pd-comb'}),e('pv','pd','vk',{bus:'pd-comb'}),e('po','pd','ov',{bus:'pd-comb'}),e('at','ar','ar-tail'),e('vt','vk','vk-tail'),e('ot','ov','ov-tail')],buses:[{id:'pd-comb',mode:'out',hub:'pd',port:'right',symmetry:false}],groups:[],drawings:[],layoutOptions:{autoSpace:true,busSymmetry:false}}]});
(async()=>{const browser=await pw.chromium.launch(launchOptions),p=await browser.newPage({viewport:{width:1600,height:1000}});p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(7000);
const reset=async(doc=fixture(),readOnly=false)=>p.evaluate(async({doc,readOnly})=>{const s=Studio.state;s.dirty=false;await Studio.activateDocument(doc,{name:'Anchors.html',readOnly});s.compact=true;s.collapsed={[s.project.pages[0].id]:new Set()};s.view={x:300,y:100,z:.2};s.visibility={status:true,relative:true,lock:true,protection:true,icons:true};s.tool='select';Studio.render();},{doc,readOnly});
const centred=()=>p.evaluate(()=>{const s=Studio.state,pg=s.project.pages[0],hub=pg.nodes.find(n=>n.title==='ПД'),ns=new Map(s.display.nodes.map(n=>[n.id,n])),es=s.display.edges.filter(e=>e.source===hub.id&&!Studio.Core.edgeRelationship(pg,e)?.annotation),ys=es.map(e=>Studio.Core.endpoint(ns.get(e.target),e.targetPort,'left').y),y=Studio.Core.endpoint(ns.get(hub.id),es[0].sourcePort,'right').y;return Math.abs(y-(Math.min(...ys)+Math.max(...ys))/2)<.01;});
const controls=async id=>p.locator('[data-node="'+id+'"]').evaluate(el=>{const node=el.getBoundingClientRect(),stage=document.querySelector('#stage').getBoundingClientRect();return {node:{y:node.top,bottom:node.bottom},below:el.classList.contains('status-controls-below'),items:[...el.querySelectorAll('.status-capsule,.collapse-node')].map(c=>{const r=c.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height/2;return {y:r.top,bottom:r.bottom,offset:r.bottom-node.top,offscreen:r.bottom<=stage.top,hit:document.elementFromPoint(x,y)?.closest('.status-capsule,.collapse-node')===c};})};});
try{await p.goto('file:///'+B.replaceAll('\\','/')+'/Pipeline-Studio.html');await p.waitForSelector('#home-new');await reset();const authored=await p.evaluate(()=>JSON.stringify({pages:Studio.state.project.pages,materials:Studio.state.project.materials}));
 for(const reader of [false,true]){await reset(fixture(),reader);for(const folded of [false,true,false,true]){await p.locator('#dock [data-action="'+(folded?'collapse-all':'expand-all')+'"]').click();check('Hub stays centred after '+(folded?'collapse':'expand')+' in '+(reader?'reader':'editor'),await centred());}}
 check('Folding and centring preserve document data',await p.evaluate(()=>JSON.stringify({pages:Studio.state.project.pages,materials:Studio.state.project.materials}))===authored);
 for(const z of [.25,1,2,4]){await p.evaluate(z=>{const s=Studio.state,n=s.display.nodes.find(n=>n.id==='vk');s.view={x:300,y:120-n.y*z,z};Studio.render();},z);const before=await controls('vk');let stable=true;for(const top of [90,45,10,-20,-80,120]){await p.evaluate(({z,top})=>{const s=Studio.state,n=s.display.nodes.find(n=>n.id==='vk');s.view.y=top-n.y*z;Studio.render();},{z,top});const now=await controls('vk');stable&&=!now.below&&now.items.length===2&&now.items.every((c,i)=>c.bottom<now.node.y&&Math.abs(c.offset-before.items[i].offset)<.01);}check('Status and fold controls keep their node offset across the top edge at zoom '+z,stable);}
 await p.evaluate(()=>{const s=Studio.state,n=s.display.nodes.find(n=>n.id==='vk');s.view={x:300,y:10-n.y*4,z:4};Studio.render();});const clipped=await controls('vk');check('Offscreen controls are clipped while the node is still partly visible',clipped.items.every(c=>c.offscreen&&!c.hit)&&clipped.node.bottom>(await p.locator('#stage').boundingBox()).y);
 await p.evaluate(()=>{const s=Studio.state,n=s.display.nodes.find(n=>n.id==='vk');s.view={x:300,y:230-n.y*4,z:4};Studio.render();});const initial=await controls('vk'),stage=await p.locator('#stage').boundingBox();await p.mouse.move(stage.x+stage.width-70,stage.y+350);await p.mouse.down({button:'middle'});await p.mouse.move(stage.x+stage.width-70,stage.y+130,{steps:12});await p.mouse.up({button:'middle'});const panned=await controls('vk');check('Actual middle-button panning keeps the controls anchored above their node',!panned.below&&panned.items.every((c,i)=>Math.abs(c.offset-initial.items[i].offset)<.01)&&Math.abs(panned.node.y-initial.node.y+220)<.1);await p.locator('#stage').screenshot({path:path.join(out,'zoom-pan.png')});
 const privateFile=process.env.STUDIO_PRIVATE_DOCUMENT,privateJson=path.join(B,'qa/user-document.json');if(privateFile||fs.existsSync(privateJson)){const doc=privateFile?JSON.parse(fs.readFileSync(privateFile,'utf8').match(/<script id="pipeline-document" type="application\/json">([\s\S]*?)<\/script>/)[1]):JSON.parse(fs.readFileSync(privateJson,'utf8'));await reset(doc);const before=await p.evaluate(()=>JSON.stringify(Studio.state.project));for(const folded of [true,false,true]){await p.locator('#dock [data-action="'+(folded?'collapse-all':'expand-all')+'"]').click();check('Private document PD stays centred after '+(folded?'collapse':'expand'),await centred());}check('Private document centring preserves all authored coordinates and materials',await p.evaluate(()=>JSON.stringify(Studio.state.project))===before);await p.evaluate(()=>Studio.fit());await p.locator('#stage').screenshot({path:path.join(out,'private-collapsed.png')});
  for(const prefix of ['ВК','ОВ']){await p.evaluate(prefix=>{const s=Studio.state,n=s.display.nodes.find(n=>n.title.startsWith(prefix));s.view={x:300-n.x*4,y:10-n.y*4,z:4};Studio.render();},prefix);const id=await p.evaluate(prefix=>Studio.state.display.nodes.find(n=>n.title.startsWith(prefix)).id,prefix),c=await controls(id);check('Private '+prefix+' controls stay clipped above the node at 400%',!c.below&&c.items.every(i=>i.bottom<c.node.y&&i.offscreen&&!i.hit));await p.locator('#stage').screenshot({path:path.join(out,prefix==='ВК'?'private-vk-pan.png':'private-ov-pan.png')});}
 }
 check('View anchor workflows produce no JavaScript errors',errors.length===0);
}catch(e){await p.screenshot({path:path.join(out,'failure.png')});throw e;}finally{fs.writeFileSync(path.join(B,'qa/browser-view-anchors.json'),JSON.stringify({checks,errors,chromium:browser.version()},null,2));await browser.close();}assert(checks.every(c=>c.pass),'View anchor regressions failed');console.log('TOTAL',checks.length);
})().catch(e=>{console.error(e);process.exitCode=1;});
