'use strict';
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{pathToFileURL}=require('url'),{playwright:pw,launchOptions}=require('./browser_runtime'),B=path.resolve(__dirname,'..'),out=path.join(B,'qa/interaction-sequences',process.env.STUDIO_INTERACTION_DOCUMENT?'private':'public');fs.mkdirSync(out,{recursive:true});
const node=(id,x,y,extra={})=>({id,title:id,type:'block',x,y,w:110,h:60,relativeLock:true,collapsible:true,materials:[],icons:[],...extra}),edge=(id,source,target,extra={})=>({id,source,target,sourcePort:'right',targetPort:'left',arrow:true,...extra});
const publicDocument=()=>({format:'pipeline-studio',schemaVersion:6,id:'interaction',title:'Проверка перетаскивания',materials:[],pages:[{id:'p',title:'Лист',collapseMode:'nodes',layoutOptions:{autoSpace:true,busSymmetry:false},nodes:[node('hub',40,720,{w:180,h:220,collapsible:false,ports:[0,1,2,3,4].map(i=>({id:'r'+i,side:'right',x:1,y:.15+i*.16}))}),...Array.from({length:4},(_,i)=>[node('d'+i,500,920-i*15,{type:'decision',h:90,branchSymmetry:true}),node('yes'+i,750,835-i*15),node('no'+i,750,1035-i*15)]).flat(),node('warning',300,1480,{w:175,h:90})],edges:[...Array.from({length:4},(_,i)=>[edge('td'+i,'hub','d'+i,{sourcePort:'r'+i}),edge('yes-e'+i,'d'+i,'yes'+i,{sourcePort:'top'}),edge('no-e'+i,'d'+i,'no'+i,{sourcePort:'bottom'})]).flat(),edge('warning-e','hub','warning',{sourcePort:'r4'})],buses:[],groups:[],drawings:[],symmetrySets:[{id:'four',edges:['td0','td1','td2','td3'],axis:'y',gap:64,enabled:true,allowCrossings:false}]}]});
const privateFile=process.env.STUDIO_INTERACTION_DOCUMENT,doc=privateFile?JSON.parse(fs.readFileSync(privateFile,'utf8').match(/<script id="pipeline-document" type="application\/json">([\s\S]*?)<\/script>/)[1]):publicDocument();
(async()=>{const browser=await pw.chromium.launch(launchOptions),p=await browser.newPage({viewport:{width:1680,height:1050}}),checks=[],errors=[],steps=[],check=(name,ok)=>{assert.ok(ok,name);checks.push(name);console.log('PASS',name);};p.setDefaultTimeout(12000);p.on('pageerror',e=>errors.push(e.message));
const snapshot=()=>p.evaluate(()=>{const s=Studio.state,pg=s.project.pages[s.pageIndex];return {audit:LayoutAudit.audit(Studio.Core,pg,s.display),positions:s.display.nodes.map(n=>({id:n.id,x:n.x,y:n.y})),bounds:Studio.Core.bounds(s.display.nodes),model:JSON.stringify(s.project),sets:pg.symmetrySets};});
const reset=async(pageIndex,compact,autoSpace)=>p.evaluate(async({doc,pageIndex,compact,autoSpace})=>{const s=Studio.state;s.dirty=s.fileDirty=false;await Studio.activateDocument(doc,{name:'Interaction copy.html',readOnly:false});s.pageIndex=pageIndex;s.compact=compact;s.project.pages[pageIndex].layoutOptions.autoSpace=autoSpace;s.collapsed=Object.fromEntries(s.project.pages.map(p=>[p.id,new Set()]));s.folded=new Set();s.collapsedRows={};s.editModes={edges:false,centers:false,connections:false,ports:false,grid:false,ortho:false,moveChain:false,shared:false};s.selected.clear();s.selectedEdges.clear();s.selectedBuses.clear();s.selectedEdge=s.selectedBus=s.selectedSegment=null;Studio.render();},{doc,pageIndex,compact,autoSpace});
const drag=async(id,dx,dy)=>{await p.evaluate(id=>{Studio.state.selected.clear();Studio.state.selectedEdges.clear();Studio.state.selectedEdge=Studio.state.selectedBus=null;Studio.state.view.z=.7;Studio.focusNode(id);},id);const box=await p.locator('#nodes>[data-node="'+id+'"] .node-body').boundingBox(),z=await p.evaluate(()=>Studio.state.view.z);assert(box,'Visible drag target '+id);const start={x:box.x+box.width/2,y:box.y+Math.min(box.height/2,25)};await p.mouse.move(start.x,start.y);await p.mouse.down();for(let i=1;i<=3;i++){await p.mouse.move(start.x+dx*z*i/3,start.y+dy*z*i/3);await p.evaluate(()=>new Promise(requestAnimationFrame));}await p.mouse.up();await p.evaluate(()=>new Promise(requestAnimationFrame));};
try{await p.goto(pathToFileURL(path.join(B,'Pipeline-Studio.html')).href);await p.waitForSelector('#home-new');await p.addScriptTag({path:path.join(B,'tests/layout_audit.js')});
for(let pageIndex=0;pageIndex<doc.pages.length;pageIndex++)for(const compact of [false,true])for(const autoSpace of [false,true]){await reset(pageIndex,compact,autoSpace);const targets=await p.evaluate(()=>{const s=Studio.state,pg=s.project.pages[s.pageIndex],set=pg.symmetrySets?.find(g=>g.enabled!==false&&g.edges.length===4);return set?set.edges.map(id=>pg.edges.find(e=>e.id===id).target):s.display.nodes.filter(n=>n.type==='decision'&&!n.locked&&!n.editLocked).slice(0,2).map(n=>n.id);});
 for(const [index,id] of targets.entries())for(const [dx,dy] of [[0,index%2?180:-180],[0,index%2?-180:180],[100,0],[-100,0]]){const before=await snapshot();await drag(id,dx,dy);const after=await snapshot(),added=await p.evaluate(({before,after})=>LayoutAudit.added(before.audit,after.audit),{before,after}),a=before.positions.find(n=>n.id===id),b=after.positions.find(n=>n.id===id);check(`Mouse drag page ${pageIndex}, compact ${compact}, spacing ${autoSpace}, ${index}, ${dx}/${dy} introduces no conflicts`,!added.length);check('Grabbed block never jumps past the pointer or in the opposite direction',Math.abs(b.x-a.x)<=Math.abs(dx)+3&&Math.abs(b.y-a.y)<=Math.abs(dy)+3&&(b.x-a.x)*dx>=-1&&(b.y-a.y)*dy>=-1);check('Symmetry stays exact after the pointer is released',after.audit.symmetry.every(g=>g.error<.01&&g.stepError<.01));steps.push({pageIndex,compact,autoSpace,id,dx,dy,actual:{x:b.x-a.x,y:b.y-a.y},newIssues:added,toast:await p.locator('#toast').innerText(),bounds:after.bounds});
 }
 const beforeFold=await snapshot();await p.locator('[data-action=collapse-all]').click();await p.locator('[data-action=expand-all]').click();const afterFold=await snapshot();check('Collapse and expand restore exact geometry after a sequence of drags',JSON.stringify(beforeFold.positions)===JSON.stringify(afterFold.positions));await p.evaluate(()=>Studio.undo());await p.evaluate(()=>Studio.redo());check('Undo and redo restore the released geometry',JSON.stringify((await snapshot()).positions)===JSON.stringify(afterFold.positions));await p.locator('#stage').screenshot({path:path.join(out,`page-${pageIndex}-${compact}-${autoSpace}.png`)});
}
await reset(0,true,true);const constraint=await p.evaluate(()=>{const pg=Studio.state.project.pages[0],set=pg.symmetrySets.find(s=>s.edges.length===4);Studio.state.selectedEdges=new Set([set.edges[0]]);Studio.state.selectedEdge=set.edges[0];Studio.render();return {id:set.id,edges:set.edges};});const inspector=await p.locator('#inspector').innerText();check('One edge shows its group, minimum gap, actual spacing and crossing permission',inspector.includes('Симметрия 4 связей')&&inspector.includes('Пересечения: запрещены')&&inspector.includes('Текущий шаг ветвей'));await p.locator('[data-open-constraint-set]').click();check('The group button selects exactly its four connections and opens their settings',await p.evaluate(ids=>Studio.state.selectedEdges.size===ids.length&&ids.every(id=>Studio.state.selectedEdges.has(id)),constraint.edges)&&await p.locator('#selected-symmetry-gap').count()===1);
await p.evaluate(()=>{const s=Studio.state;s.selectedEdges=new Set([s.project.pages[0].symmetrySets.find(g=>g.edges.length===4).edges[0]]);s.selectedEdge=[...s.selectedEdges][0];Studio.render();});const visible=await p.evaluate(()=>{const s=Studio.state;const es=[s.selectedEdge,...s.project.pages[0].edges.filter(e=>!e.bus).map(e=>e.id)];for(const id of es){const r=s.bundle.routes.get(id);if(!r)continue;const segs=Studio.Core.routeSegments(r).filter(g=>!g.terminal&&g.length>80);if(segs.length){s.selectedEdges=new Set([id]);s.selectedEdge=id;s.selected.clear();const seg=segs[0],x=(seg.a.x+seg.b.x)/2,y=(seg.a.y+seg.b.y)/2;s.view={z:1,x:400-x,y:320-y};Studio.render();return {id,index:seg.index,vertical:seg.vertical};}}});assert(visible,'A visible segment grip');const beforeSegment=await snapshot(),grip=p.locator('[data-segment-edge="'+visible.id+'"][data-segment-index="'+visible.index+'"].segment-grip'),gb=await grip.boundingBox();assert(gb);await p.mouse.move(gb.x+gb.width/2,gb.y+gb.height/2);await p.mouse.down();await p.mouse.move(gb.x+gb.width/2+(visible.vertical?-500:0),gb.y+gb.height/2+(visible.vertical?0:500),{steps:3});await p.mouse.up();const afterSegment=await snapshot();check('Dragging the actual displayed route cannot introduce crossings or enter blocks',!await p.evaluate(({a,b})=>LayoutAudit.added(a.audit,b.audit).length,{a:beforeSegment,b:afterSegment}));
const text=await p.evaluate(async()=>Studio.buildDocumentHTML(await Studio.portableProject(false))),saved=JSON.parse(text.match(/<script id="pipeline-document" type="application\/json">([\s\S]*?)<\/script>/)[1]),beforeReload=(await snapshot()).positions;await p.evaluate(async saved=>{Studio.state.dirty=false;await Studio.activateDocument(saved,{name:'Roundtrip.html',readOnly:false});Studio.render();},saved);check('Saving and reopening retains the released layout and every node',JSON.stringify(beforeReload)===JSON.stringify((await snapshot()).positions)&&saved.pages.reduce((sum,p)=>sum+p.nodes.length,0)===doc.pages.reduce((sum,p)=>sum+p.nodes.length,0));check('Interaction sequences produce no JavaScript errors',!errors.length);
}catch(error){await p.screenshot({path:path.join(out,'failure.png')});throw error;}finally{fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({privateFixture:!!privateFile,checks,errors,steps},null,2));await browser.close();}console.log('TOTAL',checks.length,'DRAGS',steps.length);
})().catch(error=>{console.error(error);process.exitCode=1;});
