'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{pathToFileURL}=require('url'),{playwright:pw,launchOptions}=require('./browser_runtime');
const B=path.resolve(__dirname,'..'),checks=[],errors=[],ok=(name,v)=>{assert(v,name);checks.push(name);console.log('PASS',name)};
const note=(id,x)=>({id,type:'note',title:'Тестовое примечание',x,y:120,w:220,h:110,fill:'#f8cecc',materials:['material'],relativeLock:true}),doc={format:'pipeline-studio',schemaVersion:6,id:'notes-regression',title:'Примечания',revision:0,materials:[],pages:[{id:'p',title:'Лист',nodes:[note('n1',120),note('n2',430)],edges:[{id:'link',source:'n1',target:'n2',sourcePort:'right',targetPort:'left',dashed:true,flow:false}],buses:[],groups:[],drawings:[]}]};
(async()=>{const browser=await pw.chromium.launch(launchOptions),p=await browser.newPage({viewport:{width:1440,height:940}});p.on('pageerror',e=>errors.push(e.message));try{
 await p.goto(pathToFileURL(path.join(B,'Pipeline-Studio.html')).href);await p.waitForSelector('#home-new');
 const reset=async d=>p.evaluate(async d=>{await Studio.activateDocument(d);Studio.state.selected=new Set([d.pages[0].nodes[0].id]);Studio.render()},d);
 await reset(doc);ok('Legacy note exposes type conversion beside its inspector heading',await p.locator('.node-type-field #node-type').count()===1&&await p.locator('#node-type').inputValue()==='note');
 const before=await p.evaluate(()=>JSON.stringify(Studio.state.project.pages[0]));await p.locator('#node-type').selectOption('comment');ok('Legacy note immediately gains the folded comment outline',await p.locator('[data-node="n1"] .comment-shape').count()===1&&await p.locator('#node-type').inputValue()==='comment');
 ok('Legacy conversion keeps formatting text coordinates materials and connections',await p.evaluate(before=>{const a=JSON.parse(before),b=Studio.state.project.pages[0];a.nodes[0].type='comment';return JSON.stringify(a)===JSON.stringify(b)},before));await p.keyboard.press('Control+z');ok('Undo restores the original note and its original outline',await p.evaluate(before=>JSON.stringify(Studio.state.project.pages[0])===before,before)&&await p.locator('[data-node="n1"] .comment-shape').count()===0);
 await p.evaluate(()=>{Studio.state.selected=new Set(['n1','n2']);Studio.render()});ok('Several legacy notes expose the same bulk type selector',await p.locator('[data-bulk-key=type]').count()===1);await p.locator('[data-bulk-key=type]').selectOption('comment');ok('Bulk conversion gives every selected note a folded outline',await p.locator('.comment-shape').count()===2);await p.keyboard.press('Control+z');ok('One undo restores all bulk-converted notes',await p.evaluate(()=>Studio.state.project.pages[0].nodes.every(n=>n.type==='note')));
 await reset({...doc,pages:[{...doc.pages[0],nodes:[{...doc.pages[0].nodes[0],editLocked:true},doc.pages[0].nodes[1]]}]});ok('Protected legacy note keeps a disabled type control',await p.locator('#node-type').isDisabled());
 const reference=process.env.STUDIO_NOTE_REFERENCE;if(reference&&fs.existsSync(reference)){const original=JSON.parse(fs.readFileSync(reference,'utf8'));for(let i=0;i<original.pages.length;i++){const ids=original.pages[i].nodes.filter(n=>n.type==='note').slice(0,2).map(n=>n.id);if(!ids.length)continue;await p.evaluate(async({d,i})=>{await Studio.activateDocument(d);Studio.state.pageIndex=i;Studio.state.collapsed={};Studio.render()}, {d:original,i});for(const id of ids){await p.evaluate(id=>Studio.focusNode(id),id);const prior=await p.evaluate(()=>JSON.stringify(Studio.state.project.pages[Studio.state.pageIndex]));await p.locator('#node-type').selectOption('comment');ok('Private reference note gains folded shape without losing its data',await p.locator('[data-node="'+id+'"] .comment-shape').count()===1&&await p.evaluate(({prior,id})=>{const a=JSON.parse(prior),b=Studio.state.project.pages[Studio.state.pageIndex];a.nodes.find(n=>n.id===id).type='comment';return JSON.stringify(a)===JSON.stringify(b)},{prior,id}));await p.keyboard.press('Control+z');}}}
 ok('Legacy note UI emits no JavaScript errors',errors.length===0);
 }finally{fs.writeFileSync(path.join(B,'qa/browser-legacy-notes.json'),JSON.stringify({checks,errors},null,2));await browser.close()}console.log('TOTAL',checks.length);
})().catch(e=>{console.error(e);process.exitCode=1});
