'use strict';
const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict'),{spawn}=require('child_process');
const {playwright:pw,launchOptions}=require('./browser_runtime');
const B=path.resolve(__dirname,'..'),checks=[],errors=[],check=(name,ok)=>{assert(ok,name);checks.push(name);console.log('PASS',name)};
const python=process.env.STUDIO_PYTHON||path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe');
(async()=>{
 const fixture=fs.mkdtempSync(path.join(B,'qa/local-materials-')),child=spawn(fs.existsSync(python)?python:'python',[path.join(B,'tests/local_browser_host.py'),'--fixture',fixture]);let stderr='';child.stderr.on('data',d=>stderr+=d);
 const meta=await new Promise((resolve,reject)=>{let output='';child.stdout.on('data',d=>{output+=d;if(output.includes('\n'))try{resolve(JSON.parse(output.split('\n')[0]))}catch(e){reject(e)}});child.on('exit',code=>reject(Error('Local fixture exited '+code+': '+stderr)));});
 const browser=await pw.chromium.launch(launchOptions),p=await browser.newPage({viewport:{width:1440,height:940}});let downloads=0;p.on('pageerror',e=>errors.push(e.message));p.on('download',()=>downloads++);
 const native=(route)=>p.evaluate(async route=>{const r=await fetch('/native/'+route,{method:'POST',headers:{'Content-Type':'application/json','X-Studio-Token':window.STUDIO_NATIVE.token},body:'{}'});return r.json()},route);
 const openRegistry=()=>p.evaluate(()=>Studio.registry('block'));
 try{
  fs.mkdirSync(path.join(B,'docs/images/materials-originals'),{recursive:true});await p.goto(meta.url);await p.waitForSelector('#home-open');await p.locator('#home-open').click();await p.waitForSelector('#stage');check('Native document picker records its real HTML path',await p.evaluate(()=>Studio.document.nativePath)===meta.document);
  await openRegistry();check('Registry has exactly two permanent icon commands',await p.locator('.registry-command-row button').count()===2&&await p.locator('.registry-command-row button svg').count()===2&&await p.locator('#material-relink,#material-upload,#material-folder-pick').count()===0);
  await p.locator('.modal-overlay').click({position:{x:4,y:4}});check('Clicking outside does not close materials',await p.locator('#registry-body').isVisible());
  const ids=[];for(const full of meta.files){await p.locator('#material-new-link').click();await p.locator('#mat-file-pick').click();await p.waitForFunction(()=>document.querySelector('#mat-file-path').textContent.includes('local-materials-'));check(path.basename(full)+' records the actual path automatically',await p.locator('#mat-file-path').innerText()===full);await p.locator('#mat-save').click();await p.waitForSelector('#registry-body');ids.push(await p.evaluate(name=>Studio.state.project.materials.find(m=>m.filename===name).id,path.basename(full)));}
  check('Native sources contain addresses without embedded copies or blob caches',await p.evaluate(()=>Studio.state.project.materials.length===6&&Studio.state.project.materials.every(m=>m.nativePath&&!m.asset)&&Studio.document.sessionFiles.size===0&&Studio.document.urls.size===0));
  await p.locator('#material-check').click();await p.waitForFunction(()=>!document.querySelector('#material-check').disabled);check('One click checks originals and shows all results inline',await p.locator('.source-check-state.state-ok').count()===6&&await p.locator('#audit-run').count()===0);
  await p.locator('#registry-search').fill('Word');await p.locator('[data-medit]').click();await p.locator('[data-close]').click();check('Closing source editor restores registry and search',await p.locator('#registry-search').inputValue()==='Word'&&await p.locator('#registry-body tr').count()===1);await p.locator('[data-mreplace]').click();await p.keyboard.press('Escape');check('Escape from replace restores materials instead of closing everything',await p.locator('#registry-body').isVisible());await p.locator('#registry-search').fill('');
  for(const id of ids.slice(1,4)){await p.locator('[data-mopen="'+id+'"]').click();await p.waitForTimeout(30);}const events=await native('test-events');check('Word Excel and PowerPoint open their exact originals without downloads',events.opened.length===3&&events.opened.every((e,i)=>e.path===meta.files[i+1])&&downloads===0);
  await p.locator('[data-material-action=location][data-material-id="'+ids[1]+'"]').click();check('Location shows full path and offers real Explorer action',await p.locator('#file-location-popover code').innerText()===meta.files[1]&&await p.locator('[data-location-native]').isVisible());await p.locator('[data-location-native]').click();await p.waitForTimeout(30);check('Explorer request selects the original file',(await native('test-events')).opened.some(e=>e.path===meta.files[1]&&e.folder));await p.locator('[data-location-close]').click();
  await p.locator('[data-mopen="'+ids[0]+'"]').click();check('PDF viewer references the actual local file stream',await p.locator('.modal iframe').getAttribute('src').then(s=>s.startsWith('/native/content?')));await p.locator('[data-close]').click();check('Closing preview returns to materials',await p.locator('#registry-body').isVisible());
  await p.locator('[data-mopen="'+ids[4]+'"]').click();await p.locator('video').evaluate(v=>{v.muted=true;return v.play()});await p.waitForFunction(()=>document.querySelector('video').currentTime>0);check('Video streams from the original path and plays',await p.locator('video').evaluate(v=>v.videoWidth===640&&!v.error&&!v.src.startsWith('blob:')));await p.locator('[data-close]').click();
  await p.locator('[data-mopen="'+ids[5]+'"]').click();await p.waitForFunction(()=>document.querySelector('.viewer-img')?.naturalWidth===1280);check('Image preview reads the original without a blob copy',await p.locator('.viewer-img').getAttribute('src').then(s=>s.startsWith('/native/content?')));await p.locator('[data-close]').click();
  await native('test-move');await p.locator('#material-check').click();await p.waitForFunction(()=>!document.querySelector('#material-check').disabled);check('Moving an already-viewed image is detected as missing despite earlier preview',await p.locator('[data-registry-id="'+ids[5]+'"].source-missing').count()===1&&await p.locator('.source-check-state.state-ok').count()===5);await p.locator('.modal').screenshot({path:path.join(B,'docs/images/materials-originals/missing.png')});
  await p.locator('[data-mreplace="'+ids[5]+'"]').click();await p.locator('#mat-file-pick').click();await p.waitForFunction(()=>document.querySelector('#mat-file-path').textContent.endsWith('Moved picture.png'));await p.locator('#mat-save').click();await p.waitForSelector('#registry-body');check('Replace preserves material ID and all block attachments',await p.evaluate(id=>{const s=Studio.state,m=s.project.materials.find(m=>m.id===id);return m.nativePath.endsWith('Moved picture.png')&&m.version===2&&s.project.pages[0].nodes[0].materials.includes(id)},ids[5]));await p.locator('#material-check').click();await p.waitForFunction(()=>!document.querySelector('#material-check').disabled);check('Checking after replacement confirms the new original',await p.locator('.source-check-state.state-ok').count()===6);
  await p.evaluate(()=>{const s=Studio.state;for(let i=0;i<35;i++)s.project.materials.push({id:'link'+i,kind:'link',title:'Ссылка '+i,url:'https://example.invalid/'+i});Studio.registry()});const toolbar=await p.locator('.registry-tools').boundingBox();await p.locator('.registry-scroll').evaluate(el=>el.scrollTop=700);const after=await p.locator('.registry-tools').boundingBox();check('Command bar remains visible while material rows scroll',Math.abs(toolbar.y-after.y)<1&&await p.locator('#material-check').isVisible());await p.locator('[data-medit]').first().dispatchEvent('click');await p.locator('#mat-cancel').click();check('Closing editor restores previous scroll position',await p.locator('.registry-scroll').evaluate(el=>el.scrollTop)>=690);
  await p.evaluate(()=>{Studio.state.project.materials=Studio.state.project.materials.filter(m=>!m.id.startsWith('link'));Studio.registry()});await p.locator('.modal').screenshot({path:path.join(B,'docs/images/materials-originals/registry.png')});await p.locator('[data-close]').click();check('Explicit close dismisses the registry',await p.locator('.registry-dialog').count()===0);
  await p.keyboard.press('Control+s');await p.waitForFunction(()=>!Studio.state.fileDirty);const html=fs.readFileSync(meta.document,'utf8');check('Saved final HTML contains absolute and relative paths but no session token',html.includes('nativePath')&&html.includes('nativeOpenURL')&&!html.includes(await p.evaluate(()=>window.STUDIO_NATIVE.token)));
  const reader=await browser.newPage({viewport:{width:1440,height:940}});reader.on('pageerror',e=>errors.push(e.message));reader.on('download',()=>downloads++);await reader.goto('file:///'+meta.document.replaceAll('\\','/'));await reader.waitForSelector('#stage');await reader.evaluate(()=>Studio.registry());await reader.locator('[data-mopen="'+ids[5]+'"]').click();await reader.waitForFunction(()=>document.querySelector('.viewer-img')?.naturalWidth===1280);check('Standalone final HTML loads image directly from the saved original path',await reader.locator('.viewer-img').getAttribute('src').then(s=>s.startsWith('file:')));await reader.locator('[data-close]').click();
  const popup=reader.waitForEvent('popup');await reader.locator('[data-mopen="'+ids[1]+'"]').click();const opened=await popup;await opened.waitForLoadState();check('Final HTML can open Office original through a signed local link without a download',await opened.title()==='Исходный файл открыт'&&downloads===0&&(await native('test-events')).opened.filter(e=>e.path===meta.files[1]&&!e.folder).length===2);await opened.close();await reader.close();
  check('Native material workflows emit no JavaScript errors',errors.length===0);
 }catch(e){await p.screenshot({path:path.join(B,'qa/local-materials-failure.png')});throw e}finally{fs.writeFileSync(path.join(B,'qa/browser-local-materials.json'),JSON.stringify({checks,errors,fixture,chromium:browser.version()},null,2));await browser.close();child.kill();}
 console.log('TOTAL',checks.length);
})().catch(e=>{console.error(e);process.exitCode=1});
