'use strict';
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{playwright:pw,launchOptions}=require('./browser_runtime');
const B=path.resolve(__dirname,'..'),out=path.join(B,'qa/adaptive-views');fs.mkdirSync(out,{recursive:true});const checks=[],errors=[],check=(name,ok)=>{assert.ok(ok,name);checks.push(name);console.log('PASS',name)};
const n=(id,x,y,extra={})=>({id,type:'block',title:id,x,y,w:180,h:70,relativeLock:true,collapsible:true,materials:[],icons:[],...extra}),e=(id,source,target,extra={})=>({id,source,target,sourcePort:'right',targetPort:'left',arrow:true,label:'',...extra});
const fixture=()=>({id:'adaptive',format:'pipeline-studio',schemaVersion:6,title:'Адаптивное отображение',materials:[],viewState:{compact:false,collapsed:{}},pages:[{id:'p',collapseMode:'nodes',title:'Лист',nodes:[n('pd',-240,350,{collapsible:false}),n('kr',20,190,{title:'КР'}),n('vk',20,400,{title:'ВК'}),n('ov',20,510,{title:'ОВ'}),n('kr-out',400,750),n('drawings',400,310,{type:'table',w:290,title:'Список видов чертежей',table:{widths:[290],heights:[38,38],cells:[[{text:'Принципиальные схемы'}],[{text:'Планы'}]],autoSize:false}}),n('volumes',400,630,{type:'table',w:290,title:'Вывод объёмов',table:{widths:[290],heights:[38,38],cells:[[{text:'Спецификации'}],[{text:'ВР'}]],autoSize:false}}),n('d-tail',820,330,{type:'decision',title:'Вывод из модели',branchSymmetry:false}),n('v-tail',820,660,{type:'decision'}),n('a',0,1040,{title:'Первый',collapsible:false}),n('b',550,1160,{title:'Второй',collapsible:false})],edges:[e('pk','pd','kr'),e('pv','pd','vk'),e('po','pd','ov'),e('ko','kr','kr-out'),e('vd','vk','drawings',{bus:'comb'}),e('vv','vk','volumes',{bus:'comb'}),e('od','ov','drawings',{bus:'comb'}),e('dt','drawings','d-tail'),e('vt','volumes','v-tail'),e('ab','a','b',{label:'Да',manualRouteMode:'polyline',manualRoute:[{dx:70,dy:0},{dx:70,dy:90},{dx:170,dy:90},{dx:170,dy:0},{dx:300,dy:0},{dx:300,dy:120}]})],buses:[{id:'comb',mode:'free',orientation:'vertical',symmetry:true,alignGap:64}],groups:[],drawings:[{id:'ink',type:'line',points:[{x:100,y:980},{x:350,y:980}],color:'#123456',width:2}],layoutOptions:{autoSpace:false,busSymmetry:false}}]});
(async()=>{const browser=await pw.chromium.launch(launchOptions),p=await browser.newPage({viewport:{width:1800,height:1100}});p.setDefaultTimeout(6000);p.on('pageerror',e=>errors.push(e.message));
const reset=async(doc=fixture(),readOnly=false)=>p.evaluate(async({doc,readOnly})=>{const s=Studio.state;s.dirty=false;await Studio.activateDocument(doc,{name:'Adaptive.html',readOnly});s.compact=false;s.collapsed={[s.project.pages[0].id]:new Set()};s.view={x:260,y:50,z:.8};s.tool='select';s.selectionCategory='all';s.editModes={edges:false,centers:false,connections:false,ports:false,grid:false,ortho:false,moveChain:false,shared:false};s.visibility={status:true,lock:true,relative:true,protection:true,icons:true};Studio.render();},{doc,readOnly});
const select=async(sel)=>p.evaluate(sel=>{const s=Studio.state;s.selected=new Set(sel.node||[]);s.selectedEdges=new Set(sel.edge||[]);s.selectedBuses=new Set(sel.bus||[]);s.selectedDrawings=new Set(sel.drawing||[]);s.selectedEdge=s.selectedEdges.size===1?[...s.selectedEdges][0]:null;s.selectedBus=s.selectedBuses.size===1?[...s.selectedBuses][0]:null;s.selectedDrawing=s.selectedDrawings.size===1?[...s.selectedDrawings][0]:null;s.selectedSegment=null;s.quickCell=null;s.selectionCategory='all';Studio.render();},sel);
const raw=()=>p.evaluate(()=>Studio.state.project.pages[0].nodes.map(n=>[n.id,n.x,n.y,n.offsetX||0,n.offsetY||0]));
const nonoverlap=()=>p.evaluate(()=>{const bs=Studio.state.display.pipelineBounds;return bs.every((a,i)=>bs.slice(i+1).every(b=>!(a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y)));});
try{await p.goto('file:///'+B.replaceAll('\\','/')+'/Pipeline-Studio.html');await p.waitForSelector('#home-new');await reset();
 await select({node:['vk','ov']});check('Homogeneous selection keeps presets, text and complete shared behavior',await p.locator('[data-style-preset]').count()===6&&await p.locator('[data-bulk-key=relativeLock]').count()===1&&await p.locator('[data-bulk-key=title]').getAttribute('placeholder')==='Разное');
 await p.locator('[data-style-preset=blue]').click();check('A preset updates both selected blocks and keeps their individual text',await p.evaluate(()=>{const ns=Studio.state.project.pages[0].nodes;return ns[2].fill==='#dae8fc'&&ns[3].fill==='#dae8fc'&&ns[2].title==='ВК'&&ns[3].title==='ОВ'&&!ns[1].fill}));
 await p.keyboard.press('Control+z');check('Bulk preset is one reversible operation',await p.evaluate(()=>!Studio.state.project.pages[0].nodes[2].fill));await p.locator('[data-bulk-key=locked]').selectOption('true');check('Homogeneous bulk fixation applies to every selected block',await p.evaluate(()=>Studio.state.project.pages[0].nodes[2].locked&&Studio.state.project.pages[0].nodes[3].locked));
 await reset();await select({node:['kr','vk'],edge:['ko'],bus:['comb'],drawing:['ink']});check('Mixed selection exposes common properties without connection-specific controls',await p.locator('[data-bulk-key=editLocked]').count()===1&&await p.locator('[data-bulk-key=arrow]').count()===0&&await p.locator('[data-bulk-key=fill]').count()===0);
 await p.locator('[data-bulk-key=editLocked]').selectOption('true');check('Mixed protection covers blocks, a link, a comb and a drawing',await p.evaluate(()=>{const pg=Studio.state.project.pages[0];return pg.nodes[1].editLocked&&pg.nodes[2].editLocked&&pg.edges[3].editLocked&&pg.buses[0].editLocked&&pg.drawings[0].editLocked}));await p.keyboard.press('Control+z');await p.locator('#selection-category').selectOption('node');await p.locator('[data-bulk-key=locked]').selectOption('true');check('All-blocks category fixes selected blocks while retaining the mixed selection',await p.evaluate(()=>{const pg=Studio.state.project.pages[0];return pg.nodes[1].locked&&pg.nodes[2].locked&&!pg.edges[3].locked&&Studio.state.selectedEdges.has('ko')}));
 await reset();await select({node:['drawings','volumes']});check('Several tables retain presets and their table-specific properties',await p.locator('[data-style-preset]').count()===6&&await p.locator('[data-bulk-key=tableAutoSize]').count()===1&&await p.locator('[data-bulk-key=tableWordWrap]').count()===1);await p.locator('[data-style-preset=green]').click();check('Bulk table style applies to cell presentation as well as table frames',await p.evaluate(()=>['drawings','volumes'].every(id=>{const t=Studio.state.project.pages[0].nodes.find(n=>n.id===id);return t.fill==='#d5e8d4'&&t.table.cells[0][0].fill==='transparent'&&t.table.cells[0][0].color==='#244a25'})));
 await reset();await select({node:['kr']});const idBefore=await p.evaluate(()=>JSON.stringify({n:Studio.state.project.pages[0].nodes[1],edges:Studio.state.project.pages[0].edges}));await p.locator('#node-type').selectOption('comment');await p.locator('#node-type').selectOption('decision');await p.locator('#node-type').selectOption('block');check('Visible type conversion returns the same node and connections',await p.evaluate(()=>JSON.stringify({n:Studio.state.project.pages[0].nodes[1],edges:Studio.state.project.pages[0].edges}))===idBefore);
 await reset();const edgesBefore=await p.evaluate(()=>Studio.state.project.pages[0].edges.length);await p.evaluate(()=>Studio.connectPorts('kr','right','a','left'));check('Creating an extra connection does not create or extend a comb',await p.evaluate(n=>Studio.state.project.pages[0].edges.length===n+1&&Studio.state.project.pages[0].buses.length===1&&!Studio.state.project.pages[0].edges.at(-1).bus,edgesBefore));
 await reset();await select({bus:['comb']});check('A comb has one canonical symmetry panel',await p.locator('#bus-auto-align').count()===1&&await p.locator('#selected-symmetry-persistent').count()===0&&await p.locator('#bus-crossings').count()===1);if(!await p.locator('#bus-style').isVisible())await p.locator('[data-section$=":bus-geometry"] summary').click();await p.locator('#bus-style').selectOption('wire');check('Comb line style changes the rendered rounded route',await p.evaluate(()=>Studio.state.project.pages[0].buses[0].style==='wire')&&await p.locator('.wire-edge').evaluateAll(els=>els.some(el=>el.getAttribute('d').includes('Q'))));await p.locator('#bus-style').selectOption('orthogonal');
 if(!await p.locator('[data-action=bus-symmetry-align]').isVisible())await p.locator('[data-section$=":bus-symmetry"] summary').click();await p.locator('[data-action=bus-symmetry-align]').click();check('Many-to-many alignment works for the shared drawing list and quantities',await p.evaluate(()=>{const s=Studio.state,by=new Map(s.display.nodes.map(n=>[n.id,n])),port=id=>Studio.Core.endpoint(by.get(id),'left').y,src=id=>Studio.Core.endpoint(by.get(id),'right').y;return Math.abs((src('vk')+src('ov'))/2-(port('drawings')+port('volumes'))/2)<.01&&s.project.pages[0].symmetrySets.length===0}));
 await reset();for(const root of ['vk','ov']){const before=await raw();await select({node:[root]});await p.evaluate(()=>Studio.nudge('ArrowDown',25));check('Dragging intent from '+root+' carries both roots and all shared continuations once',await p.evaluate(before=>{const ids=['vk','ov','drawings','volumes','d-tail','v-tail'],pg=Studio.state.project.pages[0];return ids.every(id=>Math.abs(pg.nodes.find(n=>n.id===id).y-before.find(n=>n[0]===id)[2]-25)<.01)},before));await reset();}
 const beforeFold=await raw();await p.locator('[data-collapse-node=ov]').click();check('Folding OV also folds VK and the whole common continuation',await p.locator('[data-node=drawings]').count()===0&&await p.locator('[data-node=volumes]').count()===0&&await p.evaluate(()=>Studio.state.collapsed.p.has('vk')&&Studio.state.collapsed.p.has('ov')));await p.locator('[data-collapse-node=vk]').click();check('Either source reopens the same shared chain without changing coordinates',await p.locator('[data-node=volumes]').count()===1&&JSON.stringify(await raw())===JSON.stringify(beforeFold));
 await reset();await select({node:['drawings']});await p.locator('[data-row-behavior]').first().check();for(const z of [.25,.5,1,2]){await p.evaluate(z=>{Studio.state.view.z=z;Studio.render();},z);check('All status, collapse and row controls scale with the diagram at zoom '+z,await p.locator('[data-node=drawings]').evaluate((el,z)=>{const cap=el.querySelector('.status-capsule'),fold=el.querySelector('.collapse-node'),row=el.querySelector('.collapse-row'),icon=cap.querySelector('svg'),r=el.getBoundingClientRect();return Math.abs(cap.getBoundingClientRect().height-30*z)<.1&&Math.abs(fold.getBoundingClientRect().height-30*z)<.1&&Math.abs(row.getBoundingClientRect().height-30*z)<.1&&Math.abs(icon.getBoundingClientRect().height-16*z)<.1&&Math.abs(fold.getBoundingClientRect().right-r.right)<2.1*z},z));}
 await reset();const authored=await raw(),baseline=await p.evaluate(()=>Studio.state.display.nodes.map(n=>[n.id,n.x,n.y]));await p.locator('#dock [data-action=layout-modes]').click();await p.locator('#layout-space').check();await p.locator('#layout-compact').check();check('Adaptive modes separate complete workflow envelopes',await nonoverlap());for(let i=0;i<4;i++){await p.locator('[data-collapse-node=kr]').click();await p.locator('[data-collapse-node=kr]').click();}check('Repeated folding and expansion stay separated and preserve authored coordinates',await nonoverlap()&&JSON.stringify(await raw())===JSON.stringify(authored));if(await p.locator('#layout-compact').count()===0)await p.locator('#dock [data-action=layout-modes]').click();await p.locator('#layout-compact').uncheck();await p.locator('#layout-space').uncheck();check('Disabling both view modes restores exactly the authored presentation',await p.evaluate(base=>JSON.stringify(Studio.state.display.nodes.map(n=>[n.id,n.x,n.y]))===JSON.stringify(base),baseline));
 await p.locator('#layout-space').check();await p.locator('#layout-compact').check();const prior=await raw();await select({node:['kr']});await p.evaluate(()=>Studio.nudge('ArrowDown',40));check('Editing in an adaptive view never bakes neighboring pipelines into the document',await p.evaluate(prior=>{const pg=Studio.state.project.pages[0];return pg.nodes.filter(n=>!['kr','kr-out'].includes(n.id)).every(n=>n.x===prior.find(v=>v[0]===n.id)[1]&&n.y===prior.find(v=>v[0]===n.id)[2]);},prior));
 await reset();await p.evaluate(()=>{Studio.state.view={x:100,y:-950,z:1};Studio.render()});await select({edge:['ab']});const hit=p.locator('.edge-hit[data-edge=ab]'),point=await hit.evaluate(el=>{const v=el.getPointAtLength(el.getTotalLength()*.55),m=el.getScreenCTM();return {x:m.a*v.x+m.c*v.y+m.e,y:m.b*v.x+m.d*v.y+m.f}});await p.mouse.dblclick(point.x,point.y);check('Double-click on the actual line opens inline label editing',await p.locator('#quick-edge-label').isVisible());await p.locator('#quick-edge-label').fill('Согласование');await p.keyboard.press('Enter');check('Inline label commit updates the selected segment and rendered text',await p.locator('.edge-label[data-edge=ab]').textContent()==='Согласование'&&await p.evaluate(()=>Number.isInteger(Studio.state.project.pages[0].edges.find(e=>e.id==='ab').labelSegment)));await p.keyboard.press('Control+z');check('Inline label editing is one undo operation',await p.locator('.edge-label[data-edge=ab]').textContent()==='Да');await p.keyboard.press('Control+y');
 const label=p.locator('.edge-label[data-edge=ab]'),box=await label.boundingBox();await p.mouse.move(box.x+box.width/2,box.y+box.height/2);await p.mouse.down();await p.mouse.move(box.x+box.width/2+30,box.y+box.height/2+20,{steps:5});await p.mouse.up();check('A label can be dragged without altering the connection route',await p.evaluate(()=>{const e=Studio.state.project.pages[0].edges.find(e=>e.id==='ab');return Math.abs(e.labelOffsetX-30)<.01&&Math.abs(e.labelOffsetY-20)<.01&&e.manualRoute.length===6}));
 await p.locator('.segment-grip[data-segment-edge=ab]').first().dispatchEvent('pointerdown',{button:0});await p.evaluate(()=>document.dispatchEvent(new PointerEvent('pointerup')));check('A square route marker explicitly selects a segment',await p.evaluate(()=>Studio.state.selectedSegment?.edge==='ab'));await p.locator('.segment-hit[data-segment-edge=ab]').first().dispatchEvent('pointerdown',{button:0});check('Clicking the line returns to whole-connection selection',await p.evaluate(()=>Studio.state.selectedEdge==='ab'&&!Studio.state.selectedSegment));await p.keyboard.press('Delete');check('Delete removes the complete connection in whole-line mode',await p.evaluate(()=>!Studio.state.project.pages[0].edges.some(e=>e.id==='ab')));await p.keyboard.press('Control+z');check('Whole-connection deletion is reversible',await p.evaluate(()=>Studio.state.project.pages[0].edges.some(e=>e.id==='ab')));
 await reset();await select({edge:['vd']});check('An individual connection exposes its inherited symmetry and an off switch',await p.locator('[data-constraint-id=comb]').isChecked());const rawBeforeRelease=await raw();await p.locator('[data-constraint-id=comb]').uncheck();check('Disabling inherited symmetry clears the canonical constraint without baking another workflow',await p.evaluate(rawBefore=>{const pg=Studio.state.project.pages[0];return !pg.buses[0].symmetry&&!pg.symmetrySets.length&&pg.nodes.find(n=>n.id==='kr').y===rawBefore.find(n=>n[0]==='kr')[2];},rawBeforeRelease));
 await reset();await p.evaluate(()=>{Studio.state.project.pages[0].edges.find(e=>e.id==='vd').editLocked=true;});await select({edge:['vd']});check('Protected connection prevents editing its inherited symmetry',await p.locator('[data-constraint-id=comb]').isDisabled());await p.evaluate(()=>{const el=document.querySelector('[data-constraint-id=comb]');el.checked=false;Studio.onChange({target:el});});check('Protection also rejects a direct constraint change event',await p.evaluate(()=>Studio.state.project.pages[0].buses[0].symmetry));
 await reset(fixture(),true);await select({edge:['vd']});check('Reader shows inherited symmetry without editing controls',await p.locator('[data-section$=":connection-constraints"] input').count()===0&&await p.locator('[data-section$=":connection-constraints"]').textContent().then(t=>t.includes('включено')));
 await reset();await p.evaluate(()=>{Studio.state.project.pages[0].layoutOptions.autoSpace=true;Studio.render();});const dragBefore=await raw(),dragBox=await p.locator('[data-node=kr]').boundingBox();await p.mouse.move(dragBox.x+dragBox.width/2,dragBox.y+dragBox.height/2);await p.mouse.down();await p.mouse.move(dragBox.x+dragBox.width/2,dragBox.y+dragBox.height/2+120,{steps:8});check('Live mouse dragging separates complete pipeline envelopes before release',await nonoverlap());await p.mouse.up();check('Mouse dragging stores only the moved workflow coordinates',await p.evaluate(before=>{const pg=Studio.state.project.pages[0];return Math.abs(pg.nodes.find(n=>n.id==='kr').y-before.find(n=>n[0]==='kr')[2]-150)<.01&&pg.nodes.filter(n=>!['kr','kr-out'].includes(n.id)).every(n=>n.y===before.find(v=>v[0]===n.id)[2]);},dragBefore));
 await reset();await select({node:['vk','ov']});await p.locator('#stage').screenshot({path:path.join(out,'selection.png')});await p.locator('#inspector').screenshot({path:path.join(out,'bulk-properties.png')});
 const privateFile=path.join(B,'qa/user-document.json');if(fs.existsSync(privateFile)){await reset(JSON.parse(fs.readFileSync(privateFile,'utf8')));const reference=await raw(),base=await p.evaluate(()=>Studio.state.display.nodes.map(n=>[n.id,n.x,n.y]));await p.evaluate(()=>{const s=Studio.state;s.project.pages[0].layoutOptions.autoSpace=true;s.compact=true;Studio.render()});check('Reference KR and shared VK/OV workflow envelopes remain separate',await nonoverlap());
  await p.evaluate(()=>{const s=Studio.state;for(let i=0;i<6;i++){for(const n of s.project.pages[0].nodes)if(n.collapsible)s.collapsed[s.project.pages[0].id].add(n.id);Studio.render();s.collapsed[s.project.pages[0].id].clear();Studio.render();}});check('Reference fold-compact-expand cycle leaves no workflow overlaps',await nonoverlap());check('Reference automatic cycles preserve all 89 authored node positions',JSON.stringify(await raw())===JSON.stringify(reference));await p.evaluate(()=>{Studio.state.project.pages[0].layoutOptions.autoSpace=false;Studio.state.compact=false;Studio.render()});check('Reference disabling view modes restores the exact original presentation',await p.evaluate(base=>JSON.stringify(Studio.state.display.nodes.map(n=>[n.id,n.x,n.y]))===JSON.stringify(base),base));
  const roles=await p.evaluate(()=>{const pg=Studio.state.project.pages[0];return Object.fromEntries(['ВК','ОВ','КР'].map(prefix=>[prefix,pg.nodes.find(n=>n.title.startsWith(prefix)).id]));});for(const id of [roles['ВК'],roles['ОВ']]){await reset(JSON.parse(fs.readFileSync(privateFile,'utf8')));const rawBefore=await raw();await select({node:[id]});await p.evaluate(()=>Studio.nudge('ArrowDown',20));check('Reference combined workflow follows source '+(id===roles['ВК']?'VK':'OV')+' completely',await p.evaluate(({roles,rawBefore})=>{const pg=Studio.state.project.pages[0],ids=new Set([roles['ВК'],roles['ОВ'],...Studio.Core.relativeDescendantsGraph(pg,roles['ВК']),...Studio.Core.relativeDescendantsGraph(pg,roles['ОВ'])]);return [...ids].every(id=>{const n=pg.nodes.find(n=>n.id===id);return n.locked||Math.abs(n.y-rawBefore.find(r=>r[0]===id)[2]-20)<.01})},{roles,rawBefore}));}
 }
 check('Adaptive view and editing workflows produce no JavaScript errors',errors.length===0);
}catch(e){await p.screenshot({path:path.join(out,'failure.png')});console.log('STATE',await p.evaluate(()=>({selected:[...Studio.state.selected],edge:Studio.state.selectedEdge,segment:Studio.state.selectedSegment,errors:document.querySelector('#toast')?.textContent})));throw e;}finally{fs.writeFileSync(path.join(B,'qa/browser-adaptive-views.json'),JSON.stringify({checks,errors,chromium:browser.version()},null,2));await browser.close();}console.log('TOTAL',checks.length);
})().catch(e=>{console.error(e);process.exitCode=1});

