'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {playwright:pw,launchOptions}=require('./browser_runtime');
const B=path.resolve(__dirname,'..'),checks=[],errors=[];
const files=[['01 Тестовый документ PDF.pdf','pdf','PDF'],['02 Тестовый документ Word.docx','document','Word'],['03 Тестовая таблица Excel.xlsx','document','Excel'],['04 Тестовая презентация.pptx','document','Презентация'],['05 Тестовое видео.webm','video','Видео'],['06 Тестовая картинка.png','image','Изображение']];
const check=(name,ok)=>{assert(ok,name);checks.push(name);console.log('PASS',name)};
const doc={format:'pipeline-studio',schemaVersion:6,id:'source-editor-tests',title:'Источники',revision:0,materials:[],pages:[{id:'p',title:'Лист',nodes:[{id:'block',title:'Материалы',type:'block',x:100,y:100,w:240,h:100,materials:[]}],edges:[],buses:[],groups:[],drawings:[],layoutOptions:{autoSpace:false}}]};
(async()=>{
 const browser=await pw.chromium.launch(launchOptions),p=await browser.newPage({viewport:{width:1440,height:940}});p.setDefaultTimeout(7000);p.on('pageerror',e=>errors.push(e.message));
 const open=async()=>{await p.evaluate(()=>Studio.registry('block'));await p.locator('#material-new-link').click()};
 const pick=async name=>{const chooser=p.waitForEvent('filechooser');await p.locator('#mat-file-pick').click();await(await chooser).setFiles(path.join(B,'documents',name));};
 const screenshot=async name=>p.locator('.modal').screenshot({path:path.join(B,'docs/images/source-editor',name+'.png')});
 try{
  fs.mkdirSync(path.join(B,'docs/images/source-editor'),{recursive:true});fs.mkdirSync(path.join(B,'qa'),{recursive:true});
  await p.goto('file:///'+B.replaceAll('\\','/')+'/Pipeline-Studio.html');await p.waitForSelector('#home-new');await p.evaluate(async d=>{await Studio.activateDocument(d,{name:'Sources.html'});window.showOpenFilePicker=undefined;},doc);
  await open();check('New source starts with file or link, without manual type, path or video settings',await p.locator('[data-source-choice]').count()===2&&await p.locator('#mat-title').isHidden()&&await p.locator('#mat-save').isDisabled()&&await p.locator('#mat-kind,#mat-time,#mat-preview,#mat-embed').count()===0);await screenshot('choose');
  await pick(files[5][0]);check('Selecting a file fills its name, type and path before saving',await p.locator('#mat-title').inputValue()===files[5][0]&&await p.locator('#mat-file-kind').innerText()===files[5][2]&&await p.locator('#mat-file-path').innerText()===files[5][0]&&await p.locator('#mat-save').isEnabled());
  check('File selection alone does not create an unattached material or undo step',await p.evaluate(()=>Studio.state.project.materials.length===0&&Studio.state.history.length===0));await p.locator('#mat-cancel').click();check('Cancel leaves the material registry and block attachments empty',await p.evaluate(()=>Studio.state.project.materials.length===0&&Studio.state.project.pages[0].nodes[0].materials.length===0));
  const ids={};for(const [name,kind,label] of files){
   await open();await pick(name);check(name+' is classified and named automatically',await p.locator('#mat-file-kind').innerText()===label&&await p.locator('#mat-title').inputValue()===name&&await p.locator('#mat-file-path').innerText()===name);
   if(kind==='pdf')await screenshot('file');const history=await p.evaluate(()=>Studio.state.history.length);await p.locator('#mat-save').click();await p.waitForSelector('#registry-body');
   ids[name]=await p.evaluate(name=>Studio.state.project.materials.find(m=>m.filename===name)?.id,name);check(name+' saves source and block attachment in one undo step',await p.evaluate(({name,kind,id,history})=>{const s=Studio.state,m=s.project.materials.find(m=>m.id===id);return m&&m.title===name&&m.kind===kind&&m.path===name&&!('startAt'in m)&&s.project.pages[0].nodes[0].materials.includes(id)&&s.history.length===history+1},{name,kind,id:ids[name],history}));
  }
  await p.locator('[data-close]').click();
  await p.evaluate(()=>Studio.undo());check('One undo removes the last file and its block attachment',await p.evaluate(id=>!Studio.state.project.materials.some(m=>m.id===id)&&!Studio.state.project.pages[0].nodes[0].materials.includes(id),ids[files[5][0]]));await p.evaluate(()=>Studio.redo());check('Redo restores the source and its block attachment',await p.evaluate(id=>Studio.state.project.materials.some(m=>m.id===id)&&Studio.state.project.pages[0].nodes[0].materials.includes(id),ids[files[5][0]]));
  await p.evaluate(id=>Studio.openMaterial(id),ids[files[0][0]]);check('Selected PDF opens directly in the viewer',await p.locator('.modal iframe').getAttribute('src').then(s=>s.startsWith('blob:')));await p.locator('[data-close]').click();
  for(const [name]of files.slice(1,4)){await p.evaluate(id=>Studio.openMaterial(id),ids[name]);const bytes=await p.evaluate(async id=>[...new Uint8Array(await(await fetch(await Studio.resolveMaterial(Studio.state.project.materials.find(m=>m.id===id)))).arrayBuffer())],ids[name]);check(name+' retains original bytes and does not download automatically',Buffer.from(bytes).equals(fs.readFileSync(path.join(B,'documents',name)))&&(await p.locator('.modal-content').innerText()).includes('Pipeline Studio.exe'));await p.locator('[data-close]').click();}
  await p.evaluate(id=>Studio.openMaterial(id),ids[files[4][0]]);await p.locator('video').evaluate(v=>{v.muted=true;return v.play()});await p.waitForFunction(()=>document.querySelector('video').currentTime>0);check('Video opens and plays from the beginning',await p.locator('video').evaluate(v=>v.videoWidth===640&&!v.error&&v.currentTime<2));await p.locator('[data-close]').click();
  await p.evaluate(id=>Studio.openMaterial(id),ids[files[5][0]]);await p.waitForFunction(()=>document.querySelector('.viewer-img')?.naturalWidth===1280);check('Image selected in the new form opens at its real dimensions',await p.locator('.viewer-img').evaluate(i=>i.naturalWidth===1280&&i.naturalHeight===720));await p.locator('[data-close]').click();
  await p.evaluate(id=>Studio.editMaterial(id),ids[files[5][0]]);await p.locator('#mat-title').fill('Картинка для проверки');await p.locator('#mat-save').click();await p.waitForSelector('#registry-body');await p.evaluate(id=>Studio.editMaterial(id),ids[files[5][0]]);check('Editing a selected file preserves its custom title and session access',await p.locator('#mat-title').inputValue()==='Картинка для проверки'&&await p.evaluate(id=>Studio.assetURL(Studio.state.project.materials.find(m=>m.id===id)).startsWith('blob:'),ids[files[5][0]]));await p.locator('#mat-cancel').click();
  await open();await p.locator('[data-source-choice=url]').click();check('External link flow contains only address and editable title',await p.locator('#mat-url').isVisible()&&await p.locator('#mat-title').isVisible()&&await p.locator('#mat-file').isHidden());await p.locator('#mat-url').fill('javascript:alert(1)');await p.locator('#mat-title').fill('Ссылка');await p.locator('#mat-save').click();check('Invalid external URL is rejected without creating a material',await p.locator('#mat-url').isVisible()&&await p.evaluate(()=>Studio.state.project.materials.length===6));
  await p.locator('#mat-url').fill('https://example.com/reference');await p.locator('#mat-title').fill('Пример ссылки');await screenshot('link');await p.locator('#mat-save').click();await p.waitForSelector('#registry-body');check('Link is saved from its URL and user title with automatic classification',await p.evaluate(()=>{const m=Studio.state.project.materials.find(m=>m.title==='Пример ссылки');return m.kind==='link'&&m.url==='https://example.com/reference'&&!m.path&&!m.startAt&&!m.embed}));
  await open();await p.locator('[data-source-choice=url]').click();await p.locator('[data-link-choice=internal]').click();await p.locator('#mat-node').selectOption('block');await p.locator('#mat-save').click();await p.waitForSelector('#registry-body');check('Internal links remain available under the link flow',await p.evaluate(()=>Studio.state.project.materials.some(m=>m.kind==='node'&&m.target.nodeId==='block')));
  // Real directory input: source file lives in a subfolder, so basename is insufficient.
  const root=path.join(B,'qa/source-editor-folder'),nested=path.join(root,'documents/references');fs.mkdirSync(nested,{recursive:true});fs.copyFileSync(path.join(B,'documents',files[0][0]),path.join(nested,files[0][0]));
  await p.locator('[data-close]').click();await p.evaluate(()=>{window.showDirectoryPicker=undefined});const chooser=p.waitForEvent('filechooser'),binding=p.evaluate(()=>Studio.bindFolder());await(await chooser).setFiles(root);await binding;
  await open();await pick(files[0][0]);check('File input resolves an existing connected-folder file to its exact subfolder path',await p.locator('#mat-file-path').innerText()==='documents/references/'+files[0][0]);await p.locator('#mat-cancel').click();
  await open();await p.locator('#mat-file-folder').click();await p.locator('[data-mat-file]').click();check('Folder selection fills the complete relative path without a manual path field',await p.locator('#mat-file-path').innerText()==='documents/references/'+files[0][0]&&await p.locator('#mat-title').inputValue()===files[0][0]);await p.locator('#mat-save').click();await p.waitForSelector('#registry-body');
  const html=await p.evaluate(async()=>Studio.buildDocumentHTML(await Studio.portableProject()));await p.evaluate(async html=>Studio.activateDocument(Studio.parseDocumentText(html),{name:'Reopened.html'}),html);
  const reconnect=p.waitForEvent('filechooser'),rebound=p.evaluate(()=>Studio.bindFolder());await(await reconnect).setFiles(root);await rebound;
  check('Saved HTML retains full relative path and folder reconnect resolves it',await p.evaluate(async()=>{const m=Studio.state.project.materials.find(m=>m.path?.startsWith('documents/references/'));return m&&(await Studio.checkMaterial(m,false,{network:false})).state==='snapshot'&&(await Studio.resolveMaterial(m)).startsWith('blob:')}));
  // File System Access branch is separate from the directory-input fallback.
  await p.evaluate(()=>{const file=[...Studio.document.files.values()][0];Studio.document.root={name:'Project',resolve:async()=>['documents','native.pdf']};window.showOpenFilePicker=async()=>[{getFile:async()=>new File([file],'native.pdf',{type:'application/pdf'})}]});await open();await p.locator('#mat-file-pick').click();await p.waitForFunction(()=>document.querySelector('#mat-file-path').textContent==='documents/native.pdf');check('Native file picker saves the path returned by the connected directory handle',await p.locator('#mat-title').inputValue()==='native.pdf'&&await p.locator('#mat-file-kind').innerText()==='PDF');await p.locator('#mat-cancel').click();
  await p.evaluate(()=>{window.showOpenFilePicker=async()=>{throw new DOMException('Cancelled','AbortError')}});await open();await p.locator('#mat-file-pick').click();check('Cancelling the native picker leaves the form usable and creates no material',await p.locator('#mat-save').isDisabled()&&await p.locator('#mat-file-pick').isEnabled());await p.locator('#mat-cancel').click();
  await p.evaluate(()=>{Studio.document.root=null;window.showOpenFilePicker=async()=>{throw new DOMException('Unavailable','SecurityError')}});await open();await pick(files[5][0]);check('Native picker permission restriction falls back to the browser file input',await p.locator('#mat-title').inputValue()===files[5][0]);await p.locator('#mat-cancel').click();
  check('Source editor and viewers emit no JavaScript errors',errors.length===0);
 }catch(e){await p.screenshot({path:path.join(B,'qa/source-editor-failure.png')});throw e}finally{fs.writeFileSync(path.join(B,'qa/browser-source-editor.json'),JSON.stringify({checks,errors,chromium:browser.version()},null,2));await browser.close()}
 console.log('TOTAL',checks.length);
})().catch(e=>{console.error(e);process.exitCode=1});
