'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{spawnSync}=require('child_process'),{playwright:pw,launchOptions}=require('./browser_runtime');
const B=path.resolve(__dirname,'..'),exe=process.env.STUDIO_DESKTOP_EXE||path.join(B,'desktop/dist/win-unpacked/Pipeline Studio.exe'),base=fs.mkdtempSync(path.join(B,'qa/desktop-browser-')),profile=path.join(base,'profile'),source=path.join(base,'Author.html'),checks=[],errors=[],requests=[],check=(name,ok)=>{assert(ok,name);checks.push(name);console.log('PASS',name)};
const doc={format:'pipeline-studio',schemaVersion:6,id:'desktop-test',title:'Оригиналы',revision:0,materials:[],pages:[{id:'p',title:'Лист',nodes:[{id:'block',type:'block',title:'Источники',x:120,y:120,w:240,h:100,materials:[]}],edges:[],buses:[],groups:[],drawings:[]}]};fs.writeFileSync(source,'<script id="pipeline-document" type="application/json">'+JSON.stringify(doc)+'</script>');
const files=fs.readdirSync(path.join(B,'documents')).filter(n=>/^0[1-6] /.test(n)).sort().map(n=>{const p=path.join(base,n);fs.copyFileSync(path.join(B,'documents',n),p);return p});
(async()=>{const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;const app=await pw._electron.launch({executablePath:exe,args:['--studio-test-profile',profile,'--studio-no-register'],env,timeout:60000}),p=await app.firstWindow();const publicShot=async(locator,target)=>{await p.evaluate(base=>{window.studioShotText=[];const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;while(n=walker.nextNode())if(n.nodeValue.includes(base)){window.studioShotText.push([n,n.nodeValue]);n.nodeValue=n.nodeValue.replaceAll(base,'C:\\Pipeline Studio\\documents')}},base);try{await locator.screenshot({path:target})}finally{await p.evaluate(()=>{for(const [n,value] of window.studioShotText)n.nodeValue=value;delete window.studioShotText})}};let downloads=0;p.on('pageerror',e=>errors.push(e.message));p.on('download',()=>downloads++);p.on('request',r=>{if(r.url().startsWith('http://127.0.0.1'))requests.push(r.url())});
try{
 fs.mkdirSync(path.join(B,'docs/images/desktop'),{recursive:true});await p.waitForSelector('#home-open');check('Actual packaged EXE starts the 0.7.16 editor',await p.locator('.version-tag').innerText()==='0.7.16');check('Renderer has isolated native API without Node access',await p.evaluate(()=>typeof STUDIO_DESKTOP.call==='function'&&STUDIO_DESKTOP.platform==='win32'&&typeof require==='undefined'&&typeof process==='undefined'&&!window.STUDIO_NATIVE));
 await app.evaluate(({dialog,shell},{source,files})=>{global.studioQA={queue:[source,...files],opened:[]};dialog.showOpenDialog=async()=>{const next=global.studioQA.queue.shift();return next?{canceled:false,filePaths:[next]}:{canceled:true,filePaths:[]}};shell.openPath=async p=>{global.studioQA.opened.push({p,folder:false});return ''};shell.showItemInFolder=p=>global.studioQA.opened.push({p,folder:true});},{source,files});
 await p.locator('#home-open').click();await p.waitForSelector('#stage');check('Desktop import records exact authoring HTML and keeps it editable',await p.evaluate(()=>!Studio.state.readOnly&&!!Studio.document.nativeDigest&&Studio.document.nativePath)===source);
 await p.evaluate(()=>Studio.registry('block'));const ids=[];for(const file of files){await p.locator('#material-new-link').click();await p.locator('#mat-file-pick').click();await p.waitForFunction(()=>!document.querySelector('#mat-save').disabled);assert.equal(await p.locator('#mat-file-path').innerText(),file);await p.locator('#mat-save').click();await p.waitForSelector('#registry-body');ids.push(await p.evaluate(name=>Studio.state.project.materials.find(m=>m.filename===name).id,path.basename(file)));}check('All six file types save real paths and app links automatically',await p.evaluate(()=>Studio.state.project.materials.length===6&&Studio.state.project.materials.every(m=>m.nativePath&&m.nativeOpenURL.startsWith('pipelinestudio://open?')&&!m.asset)));check('Desktop attaches originals without blob copies',await p.evaluate(()=>Studio.document.urls.size===0&&Studio.document.sessionFiles.size===0));
 await p.locator('#material-check').click();await p.waitForFunction(()=>!document.querySelector('#material-check').disabled);check('Desktop verifies availability inline without any host',await p.locator('.state-ok').count()===6&&requests.length===0);
 for(const id of ids.slice(1,4)){await p.locator('[data-mopen="'+id+'"]').click();}await p.waitForTimeout(100);const opened=await app.evaluate(()=>global.studioQA.opened);check('Desktop Word Excel and PowerPoint commands use exact originals without downloading',opened.length===3&&opened.every((e,i)=>e.p===files[i+1])&&downloads===0);
 await p.locator('[data-material-action=location][data-material-id="'+ids[1]+'"]').click();await p.locator('[data-location-native]').click();check('Desktop Explorer action uses the original location',(await app.evaluate(()=>global.studioQA.opened)).some(e=>e.folder&&e.p===files[1]));await p.locator('[data-location-close]').click();
 await p.locator('[data-mopen="'+ids[0]+'"]').click();check('Desktop PDF preview directly references original file',await p.locator('.modal iframe').getAttribute('src').then(s=>s.startsWith('file:')));await p.waitForTimeout(400);await p.screenshot({path:path.join(B,'qa/desktop-pdf.png')});await p.locator('[data-close]').click();
 await p.locator('[data-mopen="'+ids[4]+'"]').click();await p.locator('video').evaluate(v=>{v.muted=true;return v.play()});await p.waitForFunction(()=>document.querySelector('video').currentTime>0);check('Desktop video decodes and plays directly from original',await p.locator('video').evaluate(v=>v.videoWidth===640&&!v.error&&v.src.startsWith('file:')));await p.locator('[data-close]').click();
 await p.locator('[data-mopen="'+ids[5]+'"]').click();await p.waitForFunction(()=>document.querySelector('.viewer-img')?.naturalWidth===1280);check('Desktop image loads directly at original dimensions',await p.locator('.viewer-img').getAttribute('src').then(s=>s.startsWith('file:')));await p.locator('[data-close]').click();
 const moved=path.join(base,'Moved.png');fs.renameSync(files[5],moved);await p.locator('#material-check').click();await p.waitForFunction(()=>!document.querySelector('#material-check').disabled);check('Desktop detects moved original after viewing it',await p.locator('[data-registry-id="'+ids[5]+'"].source-missing').count()===1);await app.evaluate((_,moved)=>global.studioQA.queue.push(moved),moved);await p.locator('[data-mreplace="'+ids[5]+'"]').click();await p.locator('#mat-file-pick').click();await p.waitForFunction(()=>document.querySelector('#mat-file-path').textContent.endsWith('Moved.png'));await p.locator('#mat-save').click();check('Desktop replacement preserves ID and attachments',await p.evaluate(id=>Studio.state.project.pages[0].nodes[0].materials.includes(id)&&Studio.state.project.materials.find(m=>m.id===id).nativePath.endsWith('Moved.png'),ids[5]));
 await p.locator('#registry-search').fill('Word');await p.locator('[data-medit]').click();await p.keyboard.press('Escape');check('Desktop source editor returns to filtered materials',await p.locator('#registry-search').inputValue()==='Word');await p.locator('#registry-search').fill('');await p.locator('.modal-overlay').click({position:{x:4,y:4}});check('Desktop materials remain open after outside click',await p.locator('#registry-body').isVisible());await publicShot(p.locator('.modal'),path.join(B,'docs/images/desktop/materials.png'));await p.locator('[data-close]').click();
 await p.keyboard.press('Control+s');await p.waitForFunction(()=>!Studio.state.fileDirty);const html=fs.readFileSync(source,'utf8'),saved=JSON.parse(html.match(/<script id="pipeline-document" type="application\/json">(.*?)<\/script>/s)[1]);check('Desktop saves real HTML with full paths and signed app links',saved.materials.every(m=>m.nativePath&&m.nativeOpenURL.startsWith('pipelinestudio://'))&&!html.includes('window.STUDIO_NATIVE='));
 const before=(await app.evaluate(()=>global.studioQA.opened)).length,uri=saved.materials.find(m=>m.id===ids[1]).nativeOpenURL;const second=spawnSync(exe,['--studio-test-profile',profile,'--studio-no-register',uri],{env,timeout:30000});assert.equal(second.status,0);await p.waitForTimeout(150);check('A second EXE launch opens signed original in the running app',(await app.evaluate(()=>global.studioQA.opened)).length===before+1);
 const viewer=await pw.chromium.launch(launchOptions),htmlPage=await viewer.newPage();htmlPage.on('pageerror',e=>errors.push(e.message));try{await htmlPage.goto(require('url').pathToFileURL(source).href);await htmlPage.waitForSelector('#stage');await htmlPage.evaluate(()=>{window.studioFolderLaunch='';window.open=url=>{window.studioFolderLaunch=url;return null};Studio.registry()});await htmlPage.locator('[data-material-action=location][data-material-id="'+ids[5]+'"]').click();check('Saved HTML offers the same Explorer command without a folder picker',await htmlPage.locator('[data-location-native]').innerText()==='Показать в Проводнике'&&await htmlPage.locator('[data-location-list]').count()===0);await htmlPage.locator('[data-location-native]').click();const launch=await htmlPage.evaluate(()=>window.studioFolderLaunch);assert.equal(new URL(launch).searchParams.get('action'),'folder');const dispatch=spawnSync(exe,['--studio-test-profile',profile,'--studio-no-register',launch],{env,timeout:30000});assert.equal(dispatch.status,0);await p.waitForTimeout(150);check('Saved HTML Explorer link dispatches the exact original to the desktop',await app.evaluate((_,moved)=>global.studioQA.opened.some(e=>e.folder&&e.p===moved),moved));}finally{await viewer.close()}
 await app.evaluate(({shell})=>{global.studioQA.urls=[];shell.openExternal=async u=>global.studioQA.urls.push(u)});await p.evaluate(()=>{Studio.change(()=>Studio.state.project.materials.push({id:'website',kind:'link',title:'Внешний сайт',url:'https://example.invalid/studio-test'}));Studio.registry()});await p.locator('[data-mopen="website"]').click();check('Desktop website links open in the system browser',await app.evaluate(()=>global.studioQA.urls.includes('https://example.invalid/studio-test')));await p.locator('[data-close]').click();
 const copy=path.join(base,'Saved As.html');await app.evaluate(({dialog},copy)=>{dialog.showSaveDialog=async(_,options)=>{global.studioQA.saveOptions=options;return {canceled:false,filePath:copy}}},copy);await p.evaluate(()=>Studio.saveDocument(true));check('Desktop Save As defaults to the current authoring folder',path.dirname((await app.evaluate(()=>global.studioQA.saveOptions)).defaultPath)===base);check('Desktop Save As creates chosen HTML and preserves previous file',fs.existsSync(copy)&&fs.readFileSync(source,'utf8')===html&&await p.evaluate(()=>Studio.document.nativePath)===copy);
 check('Desktop operates without HTTP requests and emits no JS errors',requests.length===0&&errors.length===0);await publicShot(p.locator('body'),path.join(B,'docs/images/desktop/editor.png'));
}catch(e){await p.screenshot({path:path.join(B,'qa/desktop-failure.png')});throw e}finally{fs.writeFileSync(path.join(B,'qa/browser-desktop.json'),JSON.stringify({checks,errors,requests,fixture:base,executable:exe},null,2));await app.evaluate(({app})=>app.exit(0));await app.close().catch(()=>{});}console.log('TOTAL',checks.length);
})().catch(e=>{console.error(e);process.exitCode=1});
