'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert/strict');const {playwright:pw,launchOptions}=require('./browser_runtime');
const B=path.resolve(__dirname,'..'),folder=path.join(B,'qa/material-samples'),checks=[],errors=[],check=(name,ok)=>{assert(ok,name);checks.push(name);console.log('PASS',name)};
const doc={format:'pipeline-studio',schemaVersion:6,id:'material-tests',title:'Материалы',revision:0,materials:[],pages:[{id:'p',title:'Лист',nodes:[{id:'block',title:'Материалы',type:'block',x:100,y:100,w:240,h:100,materials:[]}],edges:[],buses:[],groups:[],drawings:[],layoutOptions:{autoSpace:false}}]};
(async()=>{if(!fs.existsSync(path.join(folder,'Sample.docx'))){console.log('SKIP synthetic material samples have not been generated');return;}const browser=await pw.chromium.launch(launchOptions),p=await browser.newPage({viewport:{width:1440,height:940}});p.on('pageerror',e=>errors.push(e.message));
const bind=async()=>{const chooserEvent=p.waitForEvent('filechooser');const binding=p.evaluate(()=>{window.showDirectoryPicker=undefined;return Studio.bindFolder()});const chooser=await chooserEvent;await chooser.setFiles(folder);await binding;};
try{await p.goto('file:///'+B.replaceAll('\\','/')+'/Pipeline-Studio.html');await p.waitForSelector('#home-new');await p.evaluate(async d=>Studio.activateDocument(d,{name:'Materials.html'}),doc);
const video=await p.evaluate(async()=>{const canvas=document.createElement('canvas');canvas.width=160;canvas.height=100;const ctx=canvas.getContext('2d'),stream=canvas.captureStream(12),chunks=[];const mime=MediaRecorder.isTypeSupported('video/webm;codecs=vp8')?'video/webm;codecs=vp8':'video/webm',rec=new MediaRecorder(stream,{mimeType:mime});rec.ondataavailable=e=>chunks.push(e.data);const stopped=new Promise(r=>rec.onstop=r);rec.start();let i=0;await new Promise(resolve=>{const timer=setInterval(()=>{ctx.fillStyle=i%2?'#dae8fc':'#d5e8d4';ctx.fillRect(0,0,160,100);ctx.fillStyle='#17365d';ctx.fillText('Pipeline Studio '+i,20,45);if(++i===10){clearInterval(timer);resolve()}},70)});rec.stop();await stopped;stream.getTracks().forEach(t=>t.stop());return [...new Uint8Array(await new Blob(chunks,{type:'video/webm'}).arrayBuffer())]});fs.writeFileSync(path.join(folder,'Sample.webm'),Buffer.from(video));
const ids={};for(const [file,mime] of [['Sample.docx','application/vnd.openxmlformats-officedocument.wordprocessingml.document'],['Sample.pptx','application/vnd.openxmlformats-officedocument.presentationml.presentation'],['Preview.pdf','application/pdf'],['Sample.png','image/png'],['Sample.webm','video/webm']]){
const bytes=fs.readFileSync(path.join(folder,file));ids[file]=await p.evaluate(async({file,mime,bytes})=>{const m=await Studio.uploadFile(new File([new Uint8Array(bytes)],file,{type:mime}));Studio.change(()=>Studio.state.project.pages[0].nodes[0].materials.push(m.id));return m.id},{file,mime,bytes:[...bytes]});}
check('Attaching Word and PowerPoint classifies both as documents',await p.evaluate(ids=>['Sample.docx','Sample.pptx'].every(k=>Studio.state.project.materials.find(m=>m.id===ids[k]).kind==='document'),ids));
await p.evaluate(id=>Studio.openMaterial(id),ids['Sample.webm']);await p.locator('video').evaluate(v=>{v.muted=true;return v.play()});await p.waitForFunction(()=>document.querySelector('video').readyState>=2&&document.querySelector('video').currentTime>0);check('Attached video decodes and plays in the portable browser',await p.locator('video').evaluate(v=>v.videoWidth===160&&!v.error));await p.locator('[data-close]').click();
await p.evaluate(id=>Studio.openMaterial(id),ids['Sample.png']);await p.waitForFunction(()=>document.querySelector('.viewer-img')?.naturalWidth===160);check('Attached image is loaded at its actual dimensions',await p.locator('.viewer-img').evaluate(img=>img.complete&&img.naturalWidth===160));await p.locator('[data-close]').click();
for(const file of ['Sample.docx','Sample.pptx']){await p.evaluate(id=>Studio.openMaterial(id),ids[file]);const bytes=await p.evaluate(async id=>[...new Uint8Array(await(await fetch(await Studio.resolveMaterial(Studio.state.project.materials.find(m=>m.id===id)))).arrayBuffer())],ids[file]);check(file+' keeps original bytes and explains native opening instead of downloading automatically',Buffer.from(bytes).equals(fs.readFileSync(path.join(folder,file)))&&(await p.locator('.modal-content').innerText()).includes('Pipeline Studio.exe'));await p.locator('[data-close]').click();}
await p.evaluate(ids=>Studio.change(()=>{const preview=Studio.state.project.materials.find(m=>m.id===ids['Preview.pdf']);for(const file of ['Sample.docx','Sample.pptx'])Studio.state.project.materials.find(m=>m.id===ids[file]).previewPath=preview.path;}),ids);
await bind();for(const file of ['Sample.docx','Sample.pptx']){await p.evaluate(id=>Studio.openMaterial(id),ids[file]);check(file+' opens its attached PDF preview',await p.locator('.modal iframe').count()===1&&await p.locator('.modal iframe').getAttribute('src').then(src=>src.startsWith('blob:')));await p.locator('[data-close]').click();}
const html=await p.evaluate(async()=>Studio.buildDocumentHTML(await Studio.portableProject(),true));await p.evaluate(async html=>Studio.activateDocument(Studio.parseDocumentText(html),{name:'Reopened.html'}),html);await bind();check('Reopening HTML and selecting the materials folder resolves every relative path',await p.evaluate(async()=>{const results=await Promise.all(Studio.state.project.materials.map(m=>Studio.checkMaterial(m,false,{network:false})));return results.every(r=>r.state==='snapshot'||r.state==='ok')}));
const cameraBefore=await p.evaluate(()=>JSON.stringify(Studio.state.view));await p.evaluate(id=>Studio.openMaterial(id),ids['Sample.webm']);await p.locator('video').evaluate(v=>{v.muted=true;return v.play()});await p.waitForFunction(()=>document.querySelector('video').currentTime>0);check('Video still plays after HTML roundtrip and folder reconnect',await p.locator('video').evaluate(v=>!v.error));await p.locator('[data-close]').click();
check('Camera remains unchanged while materials are opened',await p.evaluate(()=>JSON.stringify(Studio.state.view))===cameraBefore);check('Material workflows produce no JavaScript errors',errors.length===0);
}catch(e){await p.screenshot({path:path.join(B,'qa/materials-failure.png')});throw e}finally{fs.writeFileSync(path.join(B,'qa/browser-materials.json'),JSON.stringify({checks,errors,chromium:browser.version()},null,2));await browser.close()}console.log('TOTAL',checks.length);
})().catch(e=>{console.error(e);process.exitCode=1});
