'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{playwright:pw,launchOptions}=require('./browser_runtime');
const B=path.resolve(__dirname,'..'),out=path.join(B,'qa/status-capsules');fs.mkdirSync(out,{recursive:true});
const checks=[],errors=[],check=(name,ok)=>{assert.ok(ok,name);checks.push(name);console.log('PASS',name)};
const n=(id,x,y,extra={})=>({id,type:'block',title:id,x,y,w:220,h:74,relativeLock:true,locked:true,editLocked:true,collapsible:true,materials:[],icons:[],...extra});
const e=(id,source,target,extra={})=>({id,source,target,sourcePort:'right',targetPort:'left',arrow:true,...extra});
const fixture=()=>({format:'pipeline-studio',schemaVersion:6,id:'capsules',title:'Статусы блоков',materials:[],viewState:{compact:false,collapsed:{p:['block','condition','table']}},pages:[{id:'p',title:'Статусы',collapseMode:'nodes',nodes:[
 n('block',100,250,{title:'Проектирование'}),n('condition',445,190,{type:'decision',title:'Вывод из модели',w:190,h:144,branchSymmetry:true}),
 n('table',790,200,{type:'table',title:'Вывод объёмов',w:260,table:{widths:[260],heights:[38,38],autoSize:false,cells:[[{text:'Спецификация фундаментов'}],[{text:'Ведомость расхода стали'}]],rowIds:['r1','r2'],colIds:['c1'],rowBehavior:{r1:{collapsible:true},r2:{collapsible:true}}}}),
 ...['child','yes','no','r1-child','r2-child','shared'].map((id,i)=>n(id,1400,40+i*150,{title:'Продолжение',w:140,h:60,collapsible:false,relativeLock:false,locked:false,editLocked:false}))
 ],edges:[e('bc','block','child'),e('cy','condition','yes',{sourcePort:'top',label:'Да'}),e('cn','condition','no',{sourcePort:'bottom',label:'Нет'}),e('tr1','table','r1-child'),e('tr2','table','r2-child'),e('r1s','r1-child','shared'),e('r2s','r2-child','shared')],buses:[],groups:[],drawings:[],layoutOptions:{autoSpace:false,busSymmetry:false}}]});
(async()=>{const browser=await pw.chromium.launch(launchOptions),p=await browser.newPage({viewport:{width:1600,height:1000}});p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(7000);
const reset=async(d=fixture(),readOnly=false)=>p.evaluate(async({d,readOnly})=>{Studio.state.dirty=false;await Studio.activateDocument(d,{name:'Statuses.html',readOnly});const s=Studio.state,pg=s.project.pages[0],t=pg.nodes.find(n=>n.id==='table');if(t)for(let i=0;i<2;i++)pg.edges.find(e=>e.id==='tr'+(i+1)).sourcePort=Studio.Core.ports(t).find(p=>p.rowId===t.table.rowIds[i]&&p.side==='right').id;s.view={x:30,y:50,z:1};s.compact=false;s.visibility={status:true,lock:true,relative:true,protection:true,icons:true};s.tool='select';Studio.render();},{d,readOnly});
const flag=key=>p.locator('#node-status-popover [data-node-status-key="'+key+'"]');
const intersects=(a,b)=>a.x<b.x+b.width&&a.x+a.width>b.x&&a.y<b.y+b.height&&a.y+a.height>b.y;
try{await p.goto('file:///'+B.replaceAll('\\','/')+'/Pipeline-Studio.html');await p.waitForSelector('#home-new');await reset();
 check('Block, condition and table show separate status capsules',await p.locator('.status-capsule').count()===3&&await p.locator('.status-capsule span').count()===9);
 for(const id of ['block','condition','table']){const node=await p.locator('[data-node="'+id+'"]').boundingBox(),status=await p.locator('[data-node-status="'+id+'"]').boundingBox(),fold=await p.locator('[data-collapse-node="'+id+'"]').boundingBox();check(id+' controls leave the body and each other unobstructed',status.y+status.height<node.y&&fold.y+fold.height<node.y&&!intersects(status,fold));}
 check('Fold counter reflects the actual hidden table continuation',await p.locator('[data-collapse-node=table] span').innerText()==='3');
 await p.locator('#stage').screenshot({path:path.join(out,'all-statuses.png')});
 const boxes=await p.locator('#nodes > [data-node]').evaluateAll(els=>els.map(el=>{const r=el.getBoundingClientRect();return {x:r.x,y:r.y,right:r.right,bottom:r.bottom}}));const left=Math.min(...boxes.map(b=>b.x))-42,top=Math.min(...boxes.map(b=>b.y))-65,right=Math.max(...boxes.map(b=>b.right))+30,bottom=Math.max(...boxes.map(b=>b.bottom))+30;
 await p.screenshot({path:path.join(out,'preview.png'),clip:{x:left,y:top,width:right-left,height:bottom-top}});
 for(const id of ['block','condition','table']){const box=await p.locator('[data-node="'+id+'"]').boundingBox();await p.screenshot({path:path.join(out,id+'.png'),clip:{x:box.x-38,y:box.y-58,width:box.width+76,height:box.height+83}});}
 const beforeOpen=await p.evaluate(()=>JSON.stringify(Studio.state.project));await p.locator('[data-node-status=block]').click();check('Opening a capsule exposes distinct status names without changing data',await p.locator('#node-status-popover').innerText().then(t=>t.includes('Защита от правки')&&t.includes('Фиксация координат')&&t.includes('Перенос продолжения'))&&await p.evaluate(()=>JSON.stringify(Studio.state.project))===beforeOpen);
 check('Protected node offers removal of protection while its other settings remain disabled',!await flag('editLocked').isDisabled()&&await flag('locked').isDisabled()&&await flag('relativeLock').isDisabled());
 await flag('editLocked').uncheck();check('Removing protection preserves fixation and relative movement',await p.evaluate(()=>{const n=Studio.state.project.pages[0].nodes[0];return !n.editLocked&&n.locked&&n.relativeLock}));
 await flag('locked').uncheck();check('Fixation can be removed independently from relative movement',await p.evaluate(()=>{const n=Studio.state.project.pages[0].nodes[0];return !n.locked&&n.relativeLock}));
 await p.keyboard.press('Escape');check('Escape closes status details and restores focus without clearing selection',await p.locator('#node-status-popover').count()===0&&await p.locator('[data-node-status=block]').evaluate(el=>document.activeElement===el)&&await p.evaluate(()=>Studio.state.selected.has('block')));
 await p.evaluate(()=>Studio.undo());check('Status change is individually undoable',await p.evaluate(()=>Studio.state.project.pages[0].nodes[0].locked));await p.evaluate(()=>Studio.redo());
 const oldBox=await p.locator('[data-node-status=block]').boundingBox();await p.evaluate(()=>Studio.nudge('ArrowRight',30));const newBox=await p.locator('[data-node-status=block]').boundingBox();check('Capsule follows the node when it moves',Math.abs(newBox.x-oldBox.x-30)<.01&&Math.abs(newBox.y-oldBox.y)<.01);
 for(const z of [.25,.5,1,2]){await p.evaluate(z=>{const s=Studio.state;s.view={x:100,y:190,z};s.selected=new Set(['block']);s.project.pages[0].nodes[0].w=60;Studio.render();},z);const status=await p.locator('[data-node-status=block]').boundingBox(),fold=await p.locator('[data-collapse-node=block]').boundingBox();check('Narrow node controls scale with the diagram and stay separate at zoom '+z,Math.abs(status.height-30*z)<.1&&Math.abs(fold.height-30*z)<.1&&!intersects(status,fold));}
 await p.evaluate(()=>{Studio.state.view={x:80,y:170,z:1};Studio.render()});const ports=await p.locator('[data-node=block] [data-port]').evaluateAll(els=>els.every(el=>{const r=el.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return hit?.closest('[data-port]')===el;}));check('Status controls do not intercept connection ports',ports);
 await p.locator('[data-node-status=block]').click();const selectedBefore=await p.evaluate(()=>[...Studio.state.selected]);await p.keyboard.press('Escape');check('Opening narrow-node details also preserves selection',await p.evaluate(ids=>JSON.stringify([...Studio.state.selected])===JSON.stringify(ids),selectedBefore));
 await reset();await p.locator('[data-collapse-node=table]').click();check('Whole-chain fold opens all table branches and removes its hidden counter',await p.locator('[data-node=r1-child]').count()===1&&await p.locator('[data-node=r2-child]').count()===1&&await p.locator('[data-collapse-node=table] span').count()===0);await p.locator('[data-collapse-row]').first().click();check('Row fold hides only its own continuation and keeps the shared block',await p.locator('[data-node=r1-child]').count()===0&&await p.locator('[data-node=r2-child]').count()===1&&await p.locator('[data-node=shared]').count()===1);
 await p.locator('[data-node-status=table]').click();await flag('editLocked').uncheck();await p.keyboard.press('Escape');const toolbar=await p.locator('[data-node=table] .quick-table-tools').boundingBox(),capsule=await p.locator('[data-node-status=table]').boundingBox();check('Selected table editing commands occupy their own row above its statuses',!intersects(toolbar,capsule)&&toolbar.y+toolbar.height<capsule.y);
 await p.locator('#dock [data-action=visibility-menu]').click();await p.locator('#visibility-status').uncheck();check('Hiding capsules does not remove status behavior or folding',await p.locator('.status-capsule').count()===0&&await p.locator('[data-collapse-node=table]').count()===1&&await p.evaluate(()=>Studio.state.project.pages[0].nodes[2].locked));await p.locator('#visibility-status').check();
 await reset(fixture(),true);const beforeReader=await p.evaluate(()=>JSON.stringify(Studio.state.project));await p.locator('[data-node-status=table]').click();check('Reader sees status meanings without document editing controls',await p.locator('#node-status-popover').isVisible()&&await p.locator('#node-status-popover input').count()===0);await p.keyboard.press('Escape');await p.locator('[data-collapse-node=table]').click();check('Reader folding and status inspection leave document data unchanged',await p.evaluate(()=>JSON.stringify(Studio.state.project))===beforeReader);
 await p.evaluate(()=>Studio.preparePrint());check('Print output contains no status controls or collapse buttons',await p.locator('.print-area .status-capsule,.print-area .collapse-node').count()===0);await p.evaluate(()=>document.querySelectorAll('.print-area').forEach(el=>el.remove()));
 await reset();await p.locator('[data-node-status=block]').click();await p.evaluate(()=>{const s=Studio.state;s.view={x:0,y:0,z:1};s.project.pages[0].nodes[0].x=1100;s.project.pages[0].nodes[0].y=520;Studio.render()});check('Status popover stays inside the canvas near its right edge',await p.locator('#node-status-popover').evaluate(el=>{const p=el.getBoundingClientRect(),r=document.querySelector('#stage').getBoundingClientRect();return p.left>=r.left&&p.right<=r.right&&p.top>=r.top&&p.bottom<=r.bottom}));
 await reset();check('Opening another document clears its previous status popover',await p.locator('#node-status-popover').count()===0);
 await p.evaluate(()=>{const s=Studio.state,n=s.project.pages[0].nodes[2];n.editLocked=false;s.selected=new Set([n.id]);s.view={x:30,y:0,z:1};n.y=10;Studio.render()});check('Table controls stay above its header when the table reaches the top of the canvas',await p.locator('[data-node=table]').evaluate(el=>{const r=el.getBoundingClientRect();return el.querySelectorAll('.status-capsule').length===1&&el.querySelectorAll('.relative-badge').length===1&&!el.classList.contains('status-controls-below')&&!el.classList.contains('status-tools-below')&&[...el.querySelectorAll('.status-capsule,.collapse-node,.quick-table-tools')].every(c=>c.getBoundingClientRect().bottom<r.top)}));
 const coarse=await browser.newContext({viewport:{width:1600,height:1000},hasTouch:true,isMobile:true}),touch=await coarse.newPage();touch.on('pageerror',e=>errors.push(e.message));await touch.goto('file:///'+B.replaceAll('\\','/')+'/Pipeline-Studio.html');await touch.waitForSelector('#home-new');await touch.evaluate(async d=>{await Studio.activateDocument(d,{name:'Touch.html'});Studio.state.view={x:50,y:50,z:1};Studio.render()},fixture());check('Touch targets for status and fold controls are at least 44 pixels high',await touch.locator('.status-capsule,.collapse-node').evaluateAll(els=>els.every(el=>el.getBoundingClientRect().height>=44)));await coarse.close();
 check('Status workflows produce no JavaScript errors',errors.length===0);
}catch(e){await p.screenshot({path:path.join(out,'failure.png')});throw e;}finally{fs.writeFileSync(path.join(B,'qa/browser-status-capsules.json'),JSON.stringify({checks,errors,chromium:browser.version()},null,2));await browser.close();}console.log('TOTAL',checks.length);
})().catch(e=>{console.error(e);process.exitCode=1});
