 'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),C=require('../app/static/core'),tests=[];
const test=(name,fn)=>{fn();tests.push(name);console.log('PASS',name)};
function fixture(){return {id:'p',materials:[{id:'web',title:'Source',kind:'link',url:'https://example.invalid',version:3},{id:'keep',title:'Keep',kind:'link',url:'https://keep.invalid'}],pages:[{id:'one',nodes:[{id:'n',title:'Source text',materials:['web','keep'],html:'<b>Начало</b> <a data-open-material="web">Название источника</a>',table:{cells:[[{text:'Текст ячейки',html:"Текст <a href='#' data-open-material='web'><b>ссылки</b></a> и <a data-open-material=\"keep\">другой</a>",material:'web',materials:['keep','web'],sourceOptions:{web:{display:'custom',label:'Метка'},keep:{display:'auto'}}}]]}}]},{id:'two',nodes:[{id:'other',materials:['web']}]}]};}
test('Removal clears all sheet attachments without mutating the original',()=>{const p=fixture(),before=C.clone(p),out=C.removeMaterial(p,'web');assert.deepEqual(p,before);assert.deepEqual(out.pages.map(p=>p.nodes[0].materials),[['keep'],[]]);assert.equal(out.materials.length,1);});
test('Inline source removal preserves wording and rich text while keeping other links',()=>{const out=C.removeMaterial(fixture(),'web'),n=out.pages[0].nodes[0],c=n.table.cells[0][0];assert.equal(n.html,'<b>Начало</b> Название источника');assert.equal(c.html,'Текст <b>ссылки</b> и <a data-open-material="keep">другой</a>');assert.equal(c.text,'Текст ячейки');assert.deepEqual(C.cellMaterialIds(c),['keep']);assert.equal(c.material,undefined);assert.deepEqual(c.sourceOptions,{keep:{display:'auto'}});});
test('Deleted registry record carries its version for atomic HTTP deletion',()=>{const out=C.removeMaterial(fixture(),'web');assert.deepEqual(out.deletedMaterials,[{id:'web',version:3}]);C.normalizeV6({...out,pages:[]});assert.deepEqual(out.deletedMaterials,[{id:'web',version:3}]);});
test('Repeated removal is idempotent and successive removals retain both records',()=>{const first=C.removeMaterial(fixture(),'web');assert.deepEqual(C.removeMaterial(first,'web'),first);assert.deepEqual(C.removeMaterial(first,'keep').deletedMaterials,[{id:'web',version:3},{id:'keep',version:1}]);});
test('Removing a source leaves stable table geometry and row identifiers intact',()=>{const p=fixture(),t=p.pages[0].nodes[0].table;t.widths=[220];t.heights=[54];t.rowIds=['stable-row'];assert.deepEqual(C.removeMaterial(p,'web').pages[0].nodes[0].table.rowIds,['stable-row']);assert.deepEqual(C.removeMaterial(p,'web').pages[0].nodes[0].table.widths,[220]);});
test('Image bodies and attached image icons require replacement before removal',()=>{for(const data of [{imageMaterial:'web'},{icons:[{material:'web'}]}]){const p=fixture();Object.assign(p.pages[0].nodes[0],data);assert.throws(()=>C.removeMaterial(p,'web'),/изображение/);}});
test('Removing a preview clears the reference while retaining its original file',()=>{const p=fixture();p.materials[1].previewMaterial='web';const out=C.removeMaterial(p,'web');assert.equal(out.materials[0].id,'keep');assert.equal(out.materials[0].previewMaterial,undefined);});
fs.writeFileSync(path.join(__dirname,'../qa/model-v074.json'),JSON.stringify({passed:tests.length,tests},null,2));console.log('TOTAL',tests.length);
