'use strict';
const assert=require('node:assert/strict'),C=require('../app/static/core');
let count=0;function test(name,fn){fn();count++;console.log('PASS',name)}
const nodes=[{id:'a',x:0,y:0,w:160,h:100},{id:'b',x:800,y:260,w:160,h:100}],ns=new Map(nodes.map(n=>[n.id,n]));
const edge={id:'ab',source:'a',target:'b',sourcePort:'right',targetPort:'left',manualRouteMode:'polyline',manualRoute:[{dx:80,dy:0},{dx:80,dy:100},{dx:180,dy:100},{dx:180,dy:0},{dx:350,dy:0},{dx:350,dy:200},{dx:540,dy:200},{dx:540,dy:260}]};
const route=e=>C.simplifyRoute(C.edgePath(e,ns).points);
test('Local segment deletion preserves distant corners and both ports without mutation',()=>{const before=route(edge),snapshot=C.clone(edge),out=C.removeVisibleSegment(edge,ns,5),after=route(out);assert.deepEqual(edge,snapshot);assert.deepEqual(after.slice(0,4),before.slice(0,4));assert.deepEqual(after[0],before[0]);assert.deepEqual(after.at(-1),before.at(-1));assert(after.length<before.length&&after.length>=before.length-3);});
test('Terminal and comb segments reject deletion without changing their routes',()=>{const before=C.clone(edge);for(const i of [0,route(edge).length-2])assert.throws(()=>C.removeVisibleSegment(edge,ns,i));assert.throws(()=>C.removeVisibleSegment({...edge,bus:'comb'},ns,5));assert.deepEqual(edge,before);});
test('Dragging an interior segment preserves endpoint coordinates and right angles',()=>{const out=C.moveVisibleSegment(edge,ns,5,20),before=route(edge),after=route(out);assert.deepEqual(after[0],before[0]);assert.deepEqual(after.at(-1),before.at(-1));assert(after.every((p,i)=>!i||p.x===after[i-1].x||p.y===after[i-1].y));});
test('Label centering follows the selected vertical segment, with legacy behavior optional',()=>{const r=C.edgePath(edge,ns),seg=C.routeSegments(r)[1],p=C.labelPlacement({...edge,labelSegment:1},r);assert.equal(p.angle,-90);assert.equal(p.x,seg.a.x-7);assert.equal(p.y,(seg.a.y+seg.b.y)/2);assert.deepEqual(C.labelPlacement({...edge,labelCentered:false},r),{x:r.x,y:r.y-7,angle:0});});
test('Connected ports override grid only within the screen-space snap distance',()=>{const mode={connections:true,grid:true,gridSize:20},ids=new Set(['b']);let p=C.snapConnectedMove(nodes,[edge],ids,'b',0,-254,1,mode);assert.equal(p.dy,-260);assert.deepEqual(p.straightEdges,['ab']);p=C.snapConnectedMove(nodes,[edge],ids,'b',0,-230,1,mode);assert.equal(p.straightEdges.length,0);p=C.snapConnectedMove(nodes,[edge],ids,'b',0,-254,2,mode);assert.equal(p.straightEdges.length,0);});
test('Disabled connection snap and incompatible locked axis do not straighten edges',()=>{for(const [mode,axis] of [[{connections:false},null],[{connections:true},'x']])assert.equal(C.snapConnectedMove(nodes,[edge],new Set(['b']),'b',0,-254,1,mode,axis).straightEdges.length,0);});
test('Source presentation options survive merging cells and insertion of rows',()=>{const t={widths:[160,160],heights:[0],cells:[[{text:'One',materials:['one'],sourceOptions:{one:{display:'custom',label:'Guide'}}},{text:'Two',materials:['two'],sourceOptions:{two:{display:'auto'}}}]]};const m=C.mergeTable(t,{r:0,c:0},{r:0,c:1});assert.equal(m.cells[0][0].sourceOptions.one.label,'Guide');assert.equal(m.cells[0][0].sourceOptions.two.display,'auto');const next=C.tableAxis(m,'row',0);assert.deepEqual(next.cells[1][0].sourceOptions,m.cells[0][0].sourceOptions);});
console.log('TOTAL',count);
