'use strict';
const C=require('../app/static/core'),A=require('./layout_audit'),assert=require('node:assert/strict');let count=0;
const fixture=(gap=400)=>({id:'p',collapseMode:'nodes',layoutOptions:{autoSpace:false},nodes:[{id:'table',type:'block',title:'Volumes',x:0,y:390,w:140,h:220,collapsible:false,relativeLock:true,ports:[0,1,2,3,4].map(i=>({id:'r'+i,x:1,y:.1+i*.2,side:'right'}))},...Array.from({length:4},(_,i)=>({id:'d'+i,type:'decision',title:'Output',x:140+gap,y:50+i*280,w:110,h:80,relativeLock:true})),{id:'warning',type:'block',title:'Warning',x:210,y:1350,w:150,h:90,relativeLock:true}],edges:[...Array.from({length:4},(_,i)=>({id:'e'+i,source:'table',target:'d'+i,sourcePort:'r'+i,targetPort:'left',arrow:true})),{id:'w',source:'table',target:'warning',sourcePort:'r4',targetPort:'left',arrow:true}],buses:[],groups:[],drawings:[],symmetrySets:[{id:'four',edges:['e0','e1','e2','e3'],axis:'y',gap:64,enabled:true,allowCrossings:false}]});
const view=p=>C.display(p,new Set(),false,new Set(),{autoSpace:false}),test=(name,fn)=>{fn();count++;console.log('PASS',name);},paired=(p,d)=>{const a=A.audit(C,p,d),g=a.routeSymmetry.find(g=>g.id==='four');assert.equal(g.status,'checked');assert(g.error<.01,JSON.stringify(g));assert(!a.issues.some(i=>i.ids.some(id=>/^e[0-3]$/.test(id))));};
const effective=n=>{const {offsetX=0,offsetY=0,...rest}=n;return {...rest,x:n.x+offsetX,y:n.y+offsetY};};
function manual(p){const d=view(p),ns=new Map(d.nodes.map(n=>[n.id,n]));for(const i of [2,3]){const e=p.edges[i],s=C.endpoint(ns.get(e.source),e.sourcePort,'right'),t=C.endpoint(ns.get(e.target),e.targetPort,'left'),dx=(t.x-s.x)*(i===2?.9:.45);e.manualRouteMode='polyline';e.manualRoute=[{dx,dy:0},{dx,dy:t.y-s.y}];}return p;}
if(require.main===module){
test('Saved pair lanes remain equal as horizontal clearance shrinks',()=>{for(const gap of [400,240,140,80,60]){const p=manual(fixture(400));for(const n of p.nodes.filter(n=>n.type==='decision'))n.x=140+gap;const before=C.clone(p);paired(p,view(p));assert.deepEqual(p,before);}});
test('A protected source stays stationary through repeated left and right movement',()=>{let p=manual(fixture());p.nodes[0].editLocked=true;for(const dx of [-40,-40,30,-80,80,-140,100]){const d=view(p),ids=C.dragPlan(p,['d0']).ids,plan=C.prepareMove(p,ids,'d0',d,{compact:false,options:{autoSpace:false}}),next=C.moveNodes(p,ids,dx,0,'d0',plan);paired(next,next.movement.display);assert.deepEqual(effective(next.nodes[0]),effective(p.nodes[0]));p=next;}});
test('Movement stops before it breaks a pair in an impossibly narrow corridor',()=>{const p=manual(fixture()),d=view(p),ids=C.dragPlan(p,['d0']).ids,plan=C.prepareMove(p,ids,'d0',d,{compact:false,options:{autoSpace:false}}),next=C.moveNodes(p,ids,-600,0,'d0',plan);assert(next.movement.fraction<1);assert(next.movement.limited);paired(next,next.movement.display);assert.deepEqual(effective(next.nodes[0]),effective(p.nodes[0]));assert(next.movement.display.nodes.find(n=>n.id==='d0').x>d.nodes[0].x+d.nodes[0].w);});
test('Repeated pointer pressure reuses only tested geometry and converges at a bounded cost',()=>{const p=manual(fixture()),before=C.clone(p),d=view(p),ids=C.dragPlan(p,['d0']).ids,plan=C.prepareMove(p,ids,'d0',d,{compact:false,options:{autoSpace:false}});let last;for(const dx of [-80,-200,-320,-400,-500,-600,-600,-600]){last=C.moveNodes(p,ids,dx,0,'d0',plan);paired(last,last.movement.display);assert(last.movement.checks<=3);assert(!C.geometryConflicts(last.movement.display,true,last.movement.bundle).length);}const cold=C.moveNodes(p,ids,-600,0,'d0');assert(Math.abs(last.movement.display.nodes.find(n=>n.id==='d0').x-cold.movement.display.nodes.find(n=>n.id==='d0').x)<3);const reverse=C.moveNodes(p,ids,80,0,'d0',plan);assert.equal(reverse.movement.fraction,1);paired(reverse,reverse.movement.display);assert.deepEqual(p,before);});
test('The audit compares complex routes instead of skipping non-four-point shapes',()=>{const p=fixture(),d=view(p),bundle=C.bundleRoutes(d),es=p.edges.slice(0,4),ns=new Map(d.nodes.map(n=>[n.id,n]));for(let i=0;i<2;i++){const pair=[es[i],es[3-i]];for(const e of pair){const s=C.endpoint(ns.get(e.source),e.sourcePort,'right'),t=C.endpoint(ns.get(e.target),e.targetPort,'left'),pts=[[0,0],[.3,0],[.3,-.1],[.7,-.1],[.7,1],[1,1]].map(([x,y])=>({x:s.x+x*(t.x-s.x),y:s.y+y*(t.y-s.y)}));bundle.routes.set(e.id,C.pathData(pts));}}const fake={...C,bundleRoutes:()=>bundle};assert(A.audit(fake,p,d).routeSymmetry.find(g=>g.id==='four').error<.01);bundle.routes.get('e2').points[2].x+=20;const a=A.audit(fake,p,d);assert(a.routeSymmetry.find(g=>g.id==='four').error>.01);assert(a.issues.some(i=>i.kind==='route-symmetry'));});
test('The geometry guard reports a failed joint route instead of accepting fallback',()=>{const p=fixture(12),d=view(p),b=C.bundleRoutes(d);assert(b.symmetryConflicts?.includes('four'));assert(C.geometryConflicts(d,true,b).includes('route-symmetry:four'));});
test('Common-port fan-out junctions remain intentional while later crossings are forbidden',()=>{const a=[{x:0,y:0},{x:100,y:0},{x:100,y:100},{x:400,y:100}],b=[{x:0,y:0},{x:50,y:0},{x:50,y:50},{x:200,y:50},{x:200,y:-50},{x:400,y:-50}];assert(C.commonRouteJunction(a,b,{x:50,y:0}));assert(!C.commonRouteJunction(a,b,{x:100,y:50}));b[0].y=10;assert(!C.commonRouteJunction(a,b,{x:50,y:0}));});
test('Four aligned links at one table port still accept safe persistent symmetry',()=>{const p=fixture();p.edges=p.edges.filter(e=>e.id!=='w');p.nodes=p.nodes.filter(n=>n.id!=='warning');for(const e of p.edges)e.sourcePort='right';p.symmetrySets=[];const aligned=C.setEdgeSymmetry(p,['e0','e1','e2','e3']);const a=A.audit(C,aligned,view(aligned));assert(!a.issues.some(i=>i.kind==='lines'||i.kind==='route-symmetry'));assert(a.routeSymmetry.every(g=>g.error<.01));});
console.log('TOTAL',count);}
module.exports={fixture:()=>manual(fixture())};
