/* Local laboratory. Every scenario starts from an immutable document snapshot. */
(async function(){
 'use strict';
 while(!window.Studio)await new Promise(resolve=>setTimeout(resolve,20));
 const C=Studio.Core,A=LayoutAudit,SC=SymmetryScenarios,original=C.clone(window.LAB_DOCUMENT),report=[];
 const css=document.createElement('style');css.textContent='#layout-lab{position:fixed;z-index:9999;left:10px;right:10px;top:8px;padding:8px;background:#fff;border:1px solid #bec9e2;border-radius:10px;box-shadow:0 2px 12px #26345d22;font:13px system-ui;display:flex;flex-wrap:wrap;gap:8px;align-items:center}#layout-lab select{max-width:420px}#layout-lab button{padding:5px 8px}#lab-results{position:fixed;z-index:9998;right:10px;top:92px;max-height:46vh;width:390px;overflow:auto;background:#fff;padding:12px;border:1px solid #bec9e2;border-radius:8px;font:12px system-ui;white-space:pre-wrap}#lab-results:empty{display:none}';document.head.append(css);
 const bar=document.createElement('div');bar.id='layout-lab';bar.innerHTML='<b>Стенд раскладки</b><select id="lab-page"></select><select id="lab-scenario"></select><label><input id="lab-compact" type="checkbox"> Уплотнение</label><label><input id="lab-space" type="checkbox"> Интервалы</label><label><input id="lab-persist" type="checkbox" checked> Постоянно</label><label><input id="lab-cross" type="checkbox"> Пересечения</label><button id="lab-run">Применить</button><button id="lab-fold">Свернуть</button><button id="lab-expand">Развернуть</button><button id="lab-focus">К участку</button><button id="lab-audit">Проверить</button><button id="lab-export">Отчёт</button><button id="lab-snapshot">Сохранить вариант</button>';document.body.append(bar);const results=document.createElement('pre');results.id='lab-results';document.body.append(results);
 const $=id=>document.getElementById(id),option=(value,title)=>{const el=document.createElement('option');el.value=value;el.textContent=title;return el;};original.pages.forEach((pg,i)=>$('lab-page').append(option(i,pg.title||'Лист '+(i+1))));let choices,baseline,blocked=null;
 const selected=()=>choices.find(s=>s.id===$('lab-scenario').value),pg=()=>Studio.state.project.pages[Studio.state.pageIndex];
 function options(){return {compact:$('lab-compact').checked,autoSpace:$('lab-space').checked,allowCrossings:$('lab-cross').checked,persistent:$('lab-persist').checked};}
 function focus(){const s=Studio.state,scenario=selected(),ids=new Set(scenario.edges.flatMap(id=>{const e=pg().edges.find(e=>e.id===id);return e?[e.source,e.target,...C.exclusiveBranches(pg(),[e.target]).flatMap(b=>[...b.ids])]:[]})),nodes=s.display.nodes.filter(n=>ids.has(n.id));if(!nodes.length){Studio.fit();return;}const b=C.bounds(nodes),stage=document.querySelector('#stage').getBoundingClientRect(),z=Math.min((stage.width-70)/(b.w+90),(stage.height-100)/(b.h+90),1.4);s.view={x:130-b.x*z,y:75-b.y*z,z};Studio.render();}
 function audit(){const d=Studio.state.display,current=A.audit(C,pg(),d),added=A.added(baseline,current),entry={scenario:selected().id,options:options(),pipelineGap:pg().layoutOptions?.pipelineGap||64,visibleNodes:current.nodes,symmetry:current.symmetry,routeSymmetry:current.routeSymmetry,existing:baseline.issues,newIssues:added,blocked,issues:current.issues,routingConflicts:current.routingConflicts};report.push(entry);const labels=ids=>ids.map(id=>pg().nodes.find(n=>n.id===id)?.title||pg().edges.find(e=>e.id===id)?.label||id).join(' ↔ ');results.textContent=(blocked?'Операция отменена: '+blocked.message+'\n\n':'')+'Видимых блоков: '+current.nodes+'\nНаложения блоков: '+current.issues.filter(i=>i.kind==='blocks').length+'\nЛиния через блок: '+current.issues.filter(i=>i.kind==='line-block').length+'\nПересечения линий: '+current.issues.filter(i=>i.kind==='lines').length+'\nОтступ между пайплайнами: '+entry.pipelineGap+' px\nОшибка парных изгибов: '+Math.max(0,...current.routeSymmetry.filter(g=>g.error!==null).map(g=>g.error)).toFixed(4)+'\nНовых относительно исходного вида: '+added.length+'\n\n'+current.issues.map(i=>i.kind+': '+labels(i.ids)).join('\n');return entry;}
 async function reset(id){const pageIndex=Number($('lab-page').value),doc=C.clone(original);Studio.state.dirty=false;Studio.state.fileDirty=false;await Studio.activateDocument(doc,{name:'Стенд — копия.html',readOnly:false});const s=Studio.state;s.pageIndex=pageIndex;s.compact=options().compact;pg().layoutOptions={...pg().layoutOptions,autoSpace:options().autoSpace};s.collapsed=Object.fromEntries(s.project.pages.map(p=>[p.id,new Set()]));s.folded=new Set();s.selected.clear();s.selectedEdges=new Set();Studio.render();baseline=A.audit(C,pg(),s.display);if(id)$('lab-scenario').value=id;const scenario=selected();blocked=null;if(scenario.edges.length)try{s.project.pages[pageIndex]=SC.apply(C,pg(),scenario,{allowCrossings:options().allowCrossings,persistent:options().persistent});}catch(error){if(error.code!=='SYMMETRY_COLLISION')throw error;blocked={message:error.message,conflicts:error.conflicts};}s.selectedEdges=new Set(scenario.edges);Studio.render();focus();return audit();}
 function populate(){choices=SC.scenarios(C,original.pages[Number($('lab-page').value)]);$('lab-scenario').replaceChildren(...choices.map(s=>option(s.id,s.title)));}
 $('lab-page').onchange=()=>{populate();return reset();};$('lab-run').onclick=()=>reset();$('lab-scenario').onchange=()=>reset();$('lab-focus').onclick=focus;$('lab-audit').onclick=audit;$('lab-fold').onclick=()=>{Studio.action('collapse-all');audit();};$('lab-expand').onclick=()=>{Studio.action('expand-all');audit();};$('lab-export').onclick=()=>{const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));link.download='layout-lab-report.json';link.click();URL.revokeObjectURL(link.href);};
 $('lab-snapshot').textContent='Скачать копию варианта';$('lab-snapshot').title='Создаёт отдельный HTML. Для обновления рабочего документа используйте «Сохранить» в редакторе EXE.';
 $('lab-snapshot').onclick=async()=>{const s=Studio.state,snapshot=C.clone(s.project);snapshot.viewState={compact:s.compact,page:s.pageIndex,collapsed:Object.fromEntries(Object.entries(s.collapsed).map(([k,v])=>[k,[...v]])),collapsedRows:Object.fromEntries(Object.entries(s.collapsedRows||{}).map(([k,v])=>[k,[...v]]))};const html=await Studio.buildDocumentHTML(snapshot),link=document.createElement('a');link.href=URL.createObjectURL(new Blob([html],{type:'text/html'}));link.download='Вариант раскладки.html';link.click();URL.revokeObjectURL(link.href);};
 let gesture=false;document.addEventListener('pointerdown',event=>{gesture=!!event.target.closest('#stage [data-node],#stage .segment-grip,#stage [data-bus-handle]');},true);document.addEventListener('pointerup',()=>{if(!gesture)return;gesture=false;requestAnimationFrame(()=>requestAnimationFrame(()=>{const entry=audit();entry.action='pointer-gesture';entry.time=new Date().toISOString();}));});
 window.LayoutLab={original,report,reset,audit,focus,choices:()=>choices};populate();await reset();window.LayoutLab.ready=true;
})();
