'use strict';
const {app,BrowserWindow,ipcMain,dialog,shell,Menu}=require('electron'),path=require('node:path'),fs=require('node:fs'),{pathToFileURL}=require('node:url'),{FileBridge,EXTENSIONS}=require('./file-bridge.cjs');
app.setName('Pipeline Studio');
const testProfile=process.argv.indexOf('--studio-test-profile');app.setPath('userData',testProfile>=0?path.resolve(process.argv[testProfile+1]):path.join(app.getPath('appData'),'Pipeline Studio'));
let win,bridge,ready=false;const pendingArgs=[],ui=path.join(__dirname,'ui','Pipeline-Studio.html'),uiURL=pathToFileURL(ui).href,hidden=process.argv.includes('--studio-hidden');
const external=async raw=>{const u=new URL(raw);if(['http:','https:'].includes(u.protocol))return shell.openExternal(u.href);if(u.protocol==='pipelinestudio:')return bridge.openURI(u.href);throw Error('Недопустимый адрес');};
const handleArgs=async args=>{const uri=args.find(a=>a.startsWith('pipelinestudio://'));if(uri){try{await bridge.openURI(uri)}catch(e){dialog.showErrorBox('Не удалось открыть оригинал',e.message)}return;}const doc=args.find(a=>path.isAbsolute(a)&&/\.(html?|json)$/i.test(a)&&fs.existsSync(a));if(doc&&win){const p=bridge.remember(doc,true),info=await bridge.metadata(p,true),source=await bridge.command('read-document',{nativePath:p});await win.webContents.executeJavaScript('Studio.activateDocument(Studio.parseDocumentText('+JSON.stringify(source.text)+'),'+JSON.stringify({name:info.filename,nativePath:p,nativeDigest:info.digest})+')');}if(win&&!hidden){if(win.isMinimized())win.restore();win.show();win.focus();}};
if(!app.requestSingleInstanceLock()){app.quit()}else{
 app.on('second-instance',(_,args)=>{if(ready)handleArgs(args).catch(e=>dialog.showErrorBox('Не удалось открыть документ',e.message));else pendingArgs.push(args);});
 app.whenReady().then(async()=>{
  if(process.platform==='win32')app.setAppUserModelId('com.pipelinestudio.desktop');
  const executable=process.env.PORTABLE_EXECUTABLE_FILE||process.execPath,root=app.isPackaged?path.dirname(executable):path.resolve(__dirname,'..');
  bridge=new FileBridge({root,state:path.join(app.getPath('userData'),'file-access.json'),picker:async(route,data)=>{const filters=route==='pick'?[{name:'Материалы',extensions:[...EXTENSIONS].map(e=>e.slice(1))}]:[{name:'Документ Pipeline Studio',extensions:route==='pick-save'?['html','htm']:['html','htm','json']}];if(route==='pick-save'){const name=data.name||'Новый процесс.html',r=await dialog.showSaveDialog(win,{title:'Сохранить документ Pipeline Studio',defaultPath:data.documentPath?path.join(path.dirname(data.documentPath),name):name,filters});return r.canceled?null:r.filePath;}const r=await dialog.showOpenDialog(win,{title:route==='pick-document'?'Открыть документ Pipeline Studio':'Выбрать оригинал',defaultPath:data.documentPath?path.dirname(data.documentPath):app.getPath('documents'),properties:['openFile'],filters});return r.canceled?null:r.filePaths[0];},opener:async(p,folder)=>{if(folder){shell.showItemInFolder(p);return;}const error=await shell.openPath(p);if(error)throw Error(error);}});
  if(app.isPackaged&&process.argv.some(a=>a.startsWith('pipelinestudio://'))){await handleArgs(process.argv);app.quit();return;}
  win=new BrowserWindow({width:1440,height:940,minWidth:900,minHeight:600,title:'Pipeline Studio',show:!hidden,backgroundColor:'#f7f8fc',icon:path.join(__dirname,'icon.ico'),webPreferences:{preload:path.join(__dirname,'preload.cjs'),nodeIntegration:false,contextIsolation:true,sandbox:true,webSecurity:true,plugins:true}});
  Menu.setApplicationMenu(null);
  ipcMain.handle('studio:file',async(event,route,data)=>{if(event.sender!==win.webContents||event.senderFrame!==event.sender.mainFrame||event.senderFrame.url!==uiURL)throw Error('Команда доступна только редактору Studio');if(route==='open-url'){const u=new URL(data.url);if(!['http:','https:'].includes(u.protocol))throw Error('Нужен HTTP / HTTPS адрес');await shell.openExternal(u.href);return {opened:true};}if(!['pick','pick-document','pick-save','stat','link','read-document','open','folder','save'].includes(route))throw Error('Неизвестная команда');return bridge.command(route,data);});
  win.webContents.on('will-navigate',(event,url)=>{if(url!==uiURL){event.preventDefault();external(url).catch(e=>dialog.showErrorBox('Не удалось открыть источник',e.message));}});
  win.webContents.setWindowOpenHandler(({url})=>{if(url!=='about:blank')external(url).catch(e=>dialog.showErrorBox('Не удалось открыть источник',e.message));return {action:'deny'};});
  win.webContents.session.setPermissionRequestHandler((contents,permission,callback,details)=>callback(contents===win.webContents&&details.isMainFrame!==false&&(!details.requestingUrl||details.requestingUrl===uiURL)&&['clipboard-read','clipboard-sanitized-write'].includes(permission)));
  win.webContents.on('will-prevent-unload',event=>{const answer=dialog.showMessageBoxSync(win,{type:'question',title:'Есть несохранённые изменения',message:'Сохранить HTML перед закрытием?',buttons:['Сохранить и закрыть','Закрыть без сохранения','Отмена'],defaultId:0,cancelId:2});if(answer===1)event.preventDefault();else if(answer===0)win.webContents.executeJavaScript('Studio.saveDocument().then(()=>!Studio.state.fileDirty)').then(saved=>{if(saved)win.close()}).catch(e=>dialog.showErrorBox('Не удалось сохранить',e.message));});
  if(!process.argv.includes('--studio-no-register')){if(app.isPackaged)app.setAsDefaultProtocolClient('pipelinestudio',executable);else app.setAsDefaultProtocolClient('pipelinestudio',process.execPath,[path.resolve(__dirname)]);}
  await win.loadFile(ui);ready=true;await handleArgs(process.argv);for(const args of pendingArgs)await handleArgs(args);
  const reportIndex=process.argv.indexOf('--studio-smoke-report');if(reportIndex>=0){const report=path.resolve(process.argv[reportIndex+1]),data=await win.webContents.executeJavaScript('({uiVersion:document.querySelector(".version-tag")?.textContent,home:Studio.state.home,readOnly:Studio.state.readOnly,nativePath:Studio.document.nativePath,pages:Studio.state.project?.pages.map(p=>({id:p.id,nodes:p.nodes.map(n=>({id:n.id,x:n.x,y:n.y,w:n.w,h:n.h}))}))})');const probe=process.argv.indexOf('--studio-probe-original');if(probe>=0)data.probe=await bridge.command('link',{nativePath:process.argv[probe+1]});fs.writeFileSync(report,JSON.stringify({version:app.getVersion(),executable,uiURL,webPreferences:win.webContents.getLastWebPreferences(),...data},null,2),{flag:'wx'});}
 });
 app.on('window-all-closed',()=>app.quit());
}
